/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error4 } from '../models/error4.js';

/**
 * Creates an instance of AdminConversationsDisconnectSharedErrorSchema
 */
interface AdminConversationsDisconnectSharedErrorSchema {
  error: Error4;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsDisconnectSharedErrorSchemaError extends ApiError<
  AdminConversationsDisconnectSharedErrorSchema
> {}
