/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { AdminConversationsConvertToPrivateErrorEnum } from '../models/adminConversationsConvertToPrivateErrorEnum.js';

/**
 * Creates an instance of AdminConversationsConvertToPrivateErrorSchema
 */
interface AdminConversationsConvertToPrivateErrorSchema {
  error: AdminConversationsConvertToPrivateErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsConvertToPrivateErrorSchemaError extends ApiError<
  AdminConversationsConvertToPrivateErrorSchema
> {}
