/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error6 } from '../models/error6.js';

/**
 * Creates an instance of AdminConversationsGetTeamsErrorSchema
 */
interface AdminConversationsGetTeamsErrorSchema {
  error: Error6;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsGetTeamsErrorSchemaError extends ApiError<
  AdminConversationsGetTeamsErrorSchema
> {}
