/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { AdminConversationsDeleteErrorEnum } from '../models/adminConversationsDeleteErrorEnum.js';

/**
 * Creates an instance of AdminConversationsDeleteErrorSchema
 */
interface AdminConversationsDeleteErrorSchema {
  error: AdminConversationsDeleteErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsDeleteErrorSchemaError extends ApiError<
  AdminConversationsDeleteErrorSchema
> {}
