/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error } from '../models/error.js';

/**
 * Creates an instance of AdminConversationsArchiveErrorSchema
 */
interface AdminConversationsArchiveErrorSchema {
  error: Error;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsArchiveErrorSchemaError extends ApiError<
  AdminConversationsArchiveErrorSchema
> {}
