/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error1 } from '../models/error1.js';

/**
 * Creates an instance of AdminConversationsConvertToPrivateErrorSchema
 */
interface AdminConversationsConvertToPrivateErrorSchema {
  error: Error1;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsConvertToPrivateErrorSchemaError extends ApiError<
  AdminConversationsConvertToPrivateErrorSchema
> {}
