/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { AdminConversationsCreateErrorEnum } from '../models/adminConversationsCreateErrorEnum.js';

/**
 * Creates an instance of AdminConversationsCreateErrorSchema
 */
interface AdminConversationsCreateErrorSchema {
  error: AdminConversationsCreateErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsCreateErrorSchemaError extends ApiError<
  AdminConversationsCreateErrorSchema
> {}
