/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error9 } from '../models/error9.js';

/**
 * Creates an instance of AdminConversationsSearchErrorSchema
 */
interface AdminConversationsSearchErrorSchema {
  error: Error9;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsSearchErrorSchemaError extends ApiError<
  AdminConversationsSearchErrorSchema
> {}
