/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error10 } from '../models/error10.js';

/**
 * Creates an instance of AdminConversationsSetConversationPrefsErrorSchema
 */
interface AdminConversationsSetConversationPrefsErrorSchema {
  error: Error10;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsSetConversationPrefsErrorSchemaError extends ApiError<
  AdminConversationsSetConversationPrefsErrorSchema
> {}
