/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error7 } from '../models/error7.js';

/**
 * Creates an instance of AdminConversationsInviteErrorSchema
 */
interface AdminConversationsInviteErrorSchema {
  error: Error7;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsInviteErrorSchemaError extends ApiError<
  AdminConversationsInviteErrorSchema
> {}
