/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { AdminConversationsRenameErrorEnum } from '../models/adminConversationsRenameErrorEnum.js';

/**
 * Creates an instance of AdminConversationsUnarchiveErrorSchema2
 */
interface AdminConversationsUnarchiveErrorSchema2 {
  error: AdminConversationsRenameErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsUnarchiveErrorSchema2Error extends ApiError<
  AdminConversationsUnarchiveErrorSchema2
> {}
