/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error5 } from '../models/error5.js';

/**
 * Creates an instance of AdminConversationsUnarchiveErrorSchema
 */
interface AdminConversationsUnarchiveErrorSchema {
  error: Error5;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsUnarchiveErrorSchemaError extends ApiError<
  AdminConversationsUnarchiveErrorSchema
> {}
