/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { AdminConversationsUnarchiveErrorEnum } from '../models/adminConversationsUnarchiveErrorEnum.js';

/**
 * Creates an instance of AdminConversationsUnarchiveErrorSchema3
 */
interface AdminConversationsUnarchiveErrorSchema3 {
  error: AdminConversationsUnarchiveErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AdminConversationsUnarchiveErrorSchema3Error extends ApiError<
  AdminConversationsUnarchiveErrorSchema3
> {}
