/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error13 } from '../models/error13.js';

/**
 * Creates an instance of AppsPermissionsRequestErrorSchema
 */
interface AppsPermissionsRequestErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error13;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AppsPermissionsRequestErrorSchemaError extends ApiError<
  AppsPermissionsRequestErrorSchema
> {}
