/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { AppsPermissionsResourcesListErrorEnum } from '../models/appsPermissionsResourcesListErrorEnum.js';

/**
 * Creates an instance of AppsPermissionsResourcesListErrorSchema
 */
interface AppsPermissionsResourcesListErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: AppsPermissionsResourcesListErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AppsPermissionsResourcesListErrorSchemaError extends ApiError<
  AppsPermissionsResourcesListErrorSchema
> {}
