/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { AppsUninstallErrorEnum } from '../models/appsUninstallErrorEnum.js';

/**
 * Creates an instance of AppsUninstallErrorSchema
 */
interface AppsUninstallErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: AppsUninstallErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AppsUninstallErrorSchemaError extends ApiError<
  AppsUninstallErrorSchema
> {}
