/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error17 } from '../models/error17.js';

/**
 * Creates an instance of AuthRevokeErrorSchema
 */
interface AuthRevokeErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error17;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AuthRevokeErrorSchemaError extends ApiError<
  AuthRevokeErrorSchema
> {}
