/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error18 } from '../models/error18.js';

/**
 * Creates an instance of AuthTestErrorSchema
 */
interface AuthTestErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error18;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class AuthTestErrorSchemaError extends ApiError<AuthTestErrorSchema> {}
