/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { BotsInfoErrorEnum } from '../models/botsInfoErrorEnum.js';

/**
 * Creates an instance of BotsInfoErrorSchema
 */
interface BotsInfoErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: BotsInfoErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class BotsInfoErrorSchemaError extends ApiError<BotsInfoErrorSchema> {}
