/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ChatMeMessageErrorEnum } from '../models/chatMeMessageErrorEnum.js';

/**
 * Creates an instance of ChatMeMessageErrorSchema
 */
interface ChatMeMessageErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: ChatMeMessageErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ChatMeMessageErrorSchemaError extends ApiError<
  ChatMeMessageErrorSchema
> {}
