/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error21 } from '../models/error21.js';

/**
 * Creates an instance of ChatDeleteScheduledMessageErrorSchema
 */
interface ChatDeleteScheduledMessageErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error21;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ChatDeleteScheduledMessageErrorSchemaError extends ApiError<
  ChatDeleteScheduledMessageErrorSchema
> {}
