/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ChatGetPermalinkErrorEnum } from '../models/chatGetPermalinkErrorEnum.js';

/**
 * Creates an instance of ChatGetPermalinkErrorSchema
 */
interface ChatGetPermalinkErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: ChatGetPermalinkErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ChatGetPermalinkErrorSchemaError extends ApiError<
  ChatGetPermalinkErrorSchema
> {}
