/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error20 } from '../models/error20.js';

/**
 * Creates an instance of ChatDeleteErrorSchema
 */
interface ChatDeleteErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error20;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ChatDeleteErrorSchemaError extends ApiError<
  ChatDeleteErrorSchema
> {}
