/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ChatScheduledMessagesListErrorEnum } from '../models/chatScheduledMessagesListErrorEnum.js';

/**
 * Creates an instance of ChatScheduledMessagesListErrorSchema
 */
interface ChatScheduledMessagesListErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: ChatScheduledMessagesListErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ChatScheduledMessagesListErrorSchemaError extends ApiError<
  ChatScheduledMessagesListErrorSchema
> {}
