/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error28 } from '../models/error28.js';

/**
 * Creates an instance of ChatUnfurlErrorSchema
 */
interface ChatUnfurlErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error28;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ChatUnfurlErrorSchemaError extends ApiError<
  ChatUnfurlErrorSchema
> {}
