/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error24 } from '../models/error24.js';

/**
 * Creates an instance of ChatPostEphemeralErrorSchema
 */
interface ChatPostEphemeralErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error24;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ChatPostEphemeralErrorSchemaError extends ApiError<
  ChatPostEphemeralErrorSchema
> {}
