/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error25 } from '../models/error25.js';

/**
 * Creates an instance of ChatPostMessageErrorSchema
 */
interface ChatPostMessageErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error25;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ChatPostMessageErrorSchemaError extends ApiError<
  ChatPostMessageErrorSchema
> {}
