/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ConversationsJoinErrorEnum } from '../models/conversationsJoinErrorEnum.js';

/**
 * Creates an instance of ConversationsJoinErrorSchema
 */
interface ConversationsJoinErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: ConversationsJoinErrorEnum;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsJoinErrorSchemaError extends ApiError<
  ConversationsJoinErrorSchema
> {}
