/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error45 } from '../models/error45.js';

/**
 * Creates an instance of ConversationsRepliesErrorSchema
 */
interface ConversationsRepliesErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error45;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsRepliesErrorSchemaError extends ApiError<
  ConversationsRepliesErrorSchema
> {}
