/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error38 } from '../models/error38.js';

/**
 * Creates an instance of ConversationsKickErrorSchema
 */
interface ConversationsKickErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error38;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsKickErrorSchemaError extends ApiError<
  ConversationsKickErrorSchema
> {}
