/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error32 } from '../models/error32.js';

/**
 * Creates an instance of ConversationsCreateErrorSchema
 */
interface ConversationsCreateErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  detail?: string;
  error: Error32;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsCreateErrorSchemaError extends ApiError<
  ConversationsCreateErrorSchema
> {}
