/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error48 } from '../models/error48.js';

/**
 * Creates an instance of ConversationsUnarchiveErrorSchema
 */
interface ConversationsUnarchiveErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error48;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsUnarchiveErrorSchemaError extends ApiError<
  ConversationsUnarchiveErrorSchema
> {}
