/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error31 } from '../models/error31.js';

/**
 * Creates an instance of ConversationsCloseErrorSchema
 */
interface ConversationsCloseErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error31;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsCloseErrorSchemaError extends ApiError<
  ConversationsCloseErrorSchema
> {}
