/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ConversationsMembersErrorEnum } from '../models/conversationsMembersErrorEnum.js';

/**
 * Creates an instance of ConversationsMembersErrorSchema
 */
interface ConversationsMembersErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: ConversationsMembersErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsMembersErrorSchemaError extends ApiError<
  ConversationsMembersErrorSchema
> {}
