/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error41 } from '../models/error41.js';

/**
 * Creates an instance of ConversationsMarkErrorSchema
 */
interface ConversationsMarkErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error41;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsMarkErrorSchemaError extends ApiError<
  ConversationsMarkErrorSchema
> {}
