/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error30 } from '../models/error30.js';

/**
 * Creates an instance of ConversationsArchiveErrorSchema
 */
interface ConversationsArchiveErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error30;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsArchiveErrorSchemaError extends ApiError<
  ConversationsArchiveErrorSchema
> {}
