/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ConversationsOpenErrorEnum } from '../models/conversationsOpenErrorEnum.js';

/**
 * Creates an instance of ConversationsOpenErrorSchema
 */
interface ConversationsOpenErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: ConversationsOpenErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsOpenErrorSchemaError extends ApiError<
  ConversationsOpenErrorSchema
> {}
