/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error33 } from '../models/error33.js';

/**
 * Creates an instance of ConversationsHistoryErrorSchema
 */
interface ConversationsHistoryErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error33;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsHistoryErrorSchemaError extends ApiError<
  ConversationsHistoryErrorSchema
> {}
