/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ConversationsRenameErrorEnum } from '../models/conversationsRenameErrorEnum.js';

/**
 * Creates an instance of ConversationsRenameErrorSchema
 */
interface ConversationsRenameErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: ConversationsRenameErrorEnum;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsRenameErrorSchemaError extends ApiError<
  ConversationsRenameErrorSchema
> {}
