/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ConversationsLeaveErrorEnum } from '../models/conversationsLeaveErrorEnum.js';

/**
 * Creates an instance of ConversationsLeaveErrorSchema
 */
interface ConversationsLeaveErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: ConversationsLeaveErrorEnum;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsLeaveErrorSchemaError extends ApiError<
  ConversationsLeaveErrorSchema
> {}
