/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ConversationsListErrorEnum } from '../models/conversationsListErrorEnum.js';

/**
 * Creates an instance of ConversationsListErrorSchema
 */
interface ConversationsListErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: ConversationsListErrorEnum;
  needed?: string;
  ok: string;
  provided?: string;
  additionalProperties?: Record<string, unknown>;
}

export class ConversationsListErrorSchemaError extends ApiError<
  ConversationsListErrorSchema
> {}
