/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of DefaultErrorTemplate
 */
interface DefaultErrorTemplate {
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class DefaultErrorTemplateError extends ApiError<DefaultErrorTemplate> {}
