/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error49 } from '../models/error49.js';

/**
 * Creates an instance of DialogOpenErrorSchema
 */
interface DialogOpenErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error49;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class DialogOpenErrorSchemaError extends ApiError<
  DialogOpenErrorSchema
> {}
