/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { DndEndSnoozeErrorEnum } from '../models/dndEndSnoozeErrorEnum.js';

/**
 * Creates an instance of DndEndSnoozeErrorSchema
 */
interface DndEndSnoozeErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: DndEndSnoozeErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class DndEndSnoozeErrorSchemaError extends ApiError<
  DndEndSnoozeErrorSchema
> {}
