/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error50 } from '../models/error50.js';

/**
 * Creates an instance of DndEndDndErrorSchema
 */
interface DndEndDndErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error50;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class DndEndDndErrorSchemaError extends ApiError<DndEndDndErrorSchema> {}
