/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { FilesInfoErrorEnum } from '../models/filesInfoErrorEnum.js';

/**
 * Creates an instance of FilesInfoErrorSchema
 */
interface FilesInfoErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: FilesInfoErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class FilesInfoErrorSchemaError extends ApiError<FilesInfoErrorSchema> {}
