/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { FilesRevokePublicUrlErrorEnum } from '../models/filesRevokePublicUrlErrorEnum.js';

/**
 * Creates an instance of FilesRevokePublicUrlErrorSchema
 */
interface FilesRevokePublicUrlErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: FilesRevokePublicUrlErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class FilesRevokePublicUrlErrorSchemaError extends ApiError<
  FilesRevokePublicUrlErrorSchema
> {}
