/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error59 } from '../models/error59.js';

/**
 * Creates an instance of FilesSharedPublicUrlErrorSchema
 */
interface FilesSharedPublicUrlErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error59;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class FilesSharedPublicUrlErrorSchemaError extends ApiError<
  FilesSharedPublicUrlErrorSchema
> {}
