/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { FilesCommentsDeleteErrorEnum } from '../models/filesCommentsDeleteErrorEnum.js';

/**
 * Creates an instance of FilesCommentsDeleteErrorSchema
 */
interface FilesCommentsDeleteErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: FilesCommentsDeleteErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class FilesCommentsDeleteErrorSchemaError extends ApiError<
  FilesCommentsDeleteErrorSchema
> {}
