/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { FilesListErrorEnum } from '../models/filesListErrorEnum.js';

/**
 * Creates an instance of FilesListErrorSchema
 */
interface FilesListErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: FilesListErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class FilesListErrorSchemaError extends ApiError<FilesListErrorSchema> {}
