/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error57 } from '../models/error57.js';

/**
 * Creates an instance of FilesListErrorSchema
 */
interface FilesListErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error57;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class FilesListErrorSchemaError extends ApiError<FilesListErrorSchema> {}
