/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error55 } from '../models/error55.js';

/**
 * Creates an instance of FilesDeleteErrorSchema
 */
interface FilesDeleteErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error55;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class FilesDeleteErrorSchemaError extends ApiError<
  FilesDeleteErrorSchema
> {}
