/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { FilesUploadErrorEnum } from '../models/filesUploadErrorEnum.js';

/**
 * Creates an instance of FilesUploadErrorSchema
 */
interface FilesUploadErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: FilesUploadErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class FilesUploadErrorSchemaError extends ApiError<
  FilesUploadErrorSchema
> {}
