/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { MigrationExchangeErrorEnum } from '../models/migrationExchangeErrorEnum.js';

/**
 * Creates an instance of MigrationExchangeErrorSchema
 */
interface MigrationExchangeErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: MigrationExchangeErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class MigrationExchangeErrorSchemaError extends ApiError<
  MigrationExchangeErrorSchema
> {}
