/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error64 } from '../models/error64.js';

/**
 * Creates an instance of PinsRemoveErrorSchema
 */
interface PinsRemoveErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error64;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class PinsRemoveErrorSchemaError extends ApiError<
  PinsRemoveErrorSchema
> {}
