/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { PinsListErrorEnum } from '../models/pinsListErrorEnum.js';

/**
 * Creates an instance of PinsListErrorSchema
 */
interface PinsListErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: PinsListErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class PinsListErrorSchemaError extends ApiError<PinsListErrorSchema> {}
