/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error62 } from '../models/error62.js';

/**
 * Creates an instance of PinsAddErrorSchema
 */
interface PinsAddErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error62;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class PinsAddErrorSchemaError extends ApiError<PinsAddErrorSchema> {}
