/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { PinsAddErrorEnum } from '../models/pinsAddErrorEnum.js';

/**
 * Creates an instance of PinsAddErrorSchema
 */
interface PinsAddErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: PinsAddErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class PinsAddErrorSchemaError extends ApiError<PinsAddErrorSchema> {}
