/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error65 } from '../models/error65.js';

/**
 * Creates an instance of ReactionsAddErrorSchema
 */
interface ReactionsAddErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error65;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ReactionsAddErrorSchemaError extends ApiError<
  ReactionsAddErrorSchema
> {}
