/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ReactionsListErrorEnum } from '../models/reactionsListErrorEnum.js';

/**
 * Creates an instance of ReactionsListErrorSchema
 */
interface ReactionsListErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: ReactionsListErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ReactionsListErrorSchemaError extends ApiError<
  ReactionsListErrorSchema
> {}
