/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error66 } from '../models/error66.js';

/**
 * Creates an instance of ReactionsGetErrorSchema
 */
interface ReactionsGetErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error66;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ReactionsGetErrorSchemaError extends ApiError<
  ReactionsGetErrorSchema
> {}
