/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error68 } from '../models/error68.js';

/**
 * Creates an instance of ReactionsRemoveErrorSchema
 */
interface ReactionsRemoveErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error68;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class ReactionsRemoveErrorSchemaError extends ApiError<
  ReactionsRemoveErrorSchema
> {}
