/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { RemindersDeleteErrorEnum } from '../models/remindersDeleteErrorEnum.js';

/**
 * Creates an instance of RemindersInfoErrorSchema
 */
interface RemindersInfoErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: RemindersDeleteErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class RemindersInfoErrorSchemaError extends ApiError<
  RemindersInfoErrorSchema
> {}
