/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error69 } from '../models/error69.js';

/**
 * Creates an instance of RemindersAddErrorSchema
 */
interface RemindersAddErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error69;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class RemindersAddErrorSchemaError extends ApiError<
  RemindersAddErrorSchema
> {}
