/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { RemindersCompleteErrorEnum } from '../models/remindersCompleteErrorEnum.js';

/**
 * Creates an instance of RemindersCompleteErrorSchema
 */
interface RemindersCompleteErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: RemindersCompleteErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class RemindersCompleteErrorSchemaError extends ApiError<
  RemindersCompleteErrorSchema
> {}
