/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { AppsPermissionsInfoErrorEnum } from '../models/appsPermissionsInfoErrorEnum.js';

/**
 * Creates an instance of StarsListErrorSchema
 */
interface StarsListErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: AppsPermissionsInfoErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class StarsListErrorSchemaError extends ApiError<StarsListErrorSchema> {}
