/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error75 } from '../models/error75.js';

/**
 * Creates an instance of StarsAddErrorSchema
 */
interface StarsAddErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error75;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class StarsAddErrorSchemaError extends ApiError<StarsAddErrorSchema> {}
