/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error77 } from '../models/error77.js';

/**
 * Creates an instance of StarsRemoveErrorSchema
 */
interface StarsRemoveErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error77;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class StarsRemoveErrorSchemaError extends ApiError<
  StarsRemoveErrorSchema
> {}
