/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error81 } from '../models/error81.js';

/**
 * Creates an instance of TeamProfileGetErrorSchema
 */
interface TeamProfileGetErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error81;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class TeamProfileGetErrorSchemaError extends ApiError<
  TeamProfileGetErrorSchema
> {}
