/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error78 } from '../models/error78.js';

/**
 * Creates an instance of TeamAccessLogsErrorSchema
 */
interface TeamAccessLogsErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error78;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class TeamAccessLogsErrorSchemaError extends ApiError<
  TeamAccessLogsErrorSchema
> {}
