/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error74 } from '../models/error74.js';

/**
 * Creates an instance of TeamInfoErrorSchema
 */
interface TeamInfoErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error74;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class TeamInfoErrorSchemaError extends ApiError<TeamInfoErrorSchema> {}
