/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { UsersLookupByEmailErrorEnum } from '../models/usersLookupByEmailErrorEnum.js';

/**
 * Creates an instance of UsersLookupByEmailErrorSchema
 */
interface UsersLookupByEmailErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: UsersLookupByEmailErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsersLookupByEmailErrorSchemaError extends ApiError<
  UsersLookupByEmailErrorSchema
> {}
