/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { UsersProfileSetErrorEnum } from '../models/usersProfileSetErrorEnum.js';

/**
 * Creates an instance of UsersProfileSetErrorSchema
 */
interface UsersProfileSetErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: UsersProfileSetErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsersProfileSetErrorSchemaError extends ApiError<
  UsersProfileSetErrorSchema
> {}
