/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error82 } from '../models/error82.js';

/**
 * Creates an instance of UsergroupsDisableErrorSchema
 */
interface UsergroupsDisableErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error82;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsergroupsDisableErrorSchemaError extends ApiError<
  UsergroupsDisableErrorSchema
> {}
