/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { UsergroupsEnableErrorEnum } from '../models/usergroupsEnableErrorEnum.js';

/**
 * Creates an instance of UsergroupsUsersListErrorSchema
 */
interface UsergroupsUsersListErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: UsergroupsEnableErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsergroupsUsersListErrorSchemaError extends ApiError<
  UsergroupsUsersListErrorSchema
> {}
