/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { UsergroupsCreateErrorEnum } from '../models/usergroupsCreateErrorEnum.js';

/**
 * Creates an instance of UsergroupsCreateErrorSchema
 */
interface UsergroupsCreateErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: UsergroupsCreateErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsergroupsCreateErrorSchemaError extends ApiError<
  UsergroupsCreateErrorSchema
> {}
