/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error84 } from '../models/error84.js';

/**
 * Creates an instance of UsergroupsEnableErrorSchema
 */
interface UsergroupsEnableErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error84;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsergroupsEnableErrorSchemaError extends ApiError<
  UsergroupsEnableErrorSchema
> {}
