/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of UsersCountsErrorSchema
 */
interface UsersCountsErrorSchema {
  error: string;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsersCountsErrorSchemaError extends ApiError<
  UsersCountsErrorSchema
> {}
