/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error98 } from '../models/error98.js';

/**
 * Creates an instance of UsersSetPhotoErrorSchema
 */
interface UsersSetPhotoErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  /** possibly DEV/QA only */
  debug_step?: string;
  /** possibly DEV/QA only */
  dims?: string;
  error: Error98;
  ok: string;
  /** possibly DEV/QA only */
  time_ident?: number;
  additionalProperties?: Record<string, unknown>;
}

export class UsersSetPhotoErrorSchemaError extends ApiError<
  UsersSetPhotoErrorSchema
> {}
