/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error97 } from '../models/error97.js';

/**
 * Creates an instance of UsersSetActiveErrorSchema
 */
interface UsersSetActiveErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error97;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsersSetActiveErrorSchemaError extends ApiError<
  UsersSetActiveErrorSchema
> {}
