/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error93 } from '../models/error93.js';

/**
 * Creates an instance of UsersListErrorSchema
 */
interface UsersListErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error93;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsersListErrorSchemaError extends ApiError<UsersListErrorSchema> {}
