/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error99 } from '../models/error99.js';

/**
 * Creates an instance of UsersSetPresenceErrorSchema
 */
interface UsersSetPresenceErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error99;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsersSetPresenceErrorSchemaError extends ApiError<
  UsersSetPresenceErrorSchema
> {}
