/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error92 } from '../models/error92.js';

/**
 * Creates an instance of UsersInfoErrorSchema
 */
interface UsersInfoErrorSchema {
  callstack?: string;
  error: Error92;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsersInfoErrorSchemaError extends ApiError<UsersInfoErrorSchema> {}
