/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error86 } from '../models/error86.js';

/**
 * Creates an instance of UsergroupsUpdateErrorSchema
 */
interface UsergroupsUpdateErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error86;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsergroupsUpdateErrorSchemaError extends ApiError<
  UsergroupsUpdateErrorSchema
> {}
