/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { UsergroupsUpdateErrorEnum } from '../models/usergroupsUpdateErrorEnum.js';

/**
 * Creates an instance of UsergroupsUsersUpdateErrorSchema
 */
interface UsergroupsUsersUpdateErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: UsergroupsUpdateErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsergroupsUsersUpdateErrorSchemaError extends ApiError<
  UsergroupsUsersUpdateErrorSchema
> {}
