/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error12 } from '../models/error12.js';

/**
 * Creates an instance of UsersDeletePhotoErrorSchema
 */
interface UsersDeletePhotoErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error12;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsersDeletePhotoErrorSchemaError extends ApiError<
  UsersDeletePhotoErrorSchema
> {}
