/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error89 } from '../models/error89.js';

/**
 * Creates an instance of UsersConversationsErrorSchema
 */
interface UsersConversationsErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error89;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsersConversationsErrorSchemaError extends ApiError<
  UsersConversationsErrorSchema
> {}
