/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { Error96 } from '../models/error96.js';

/**
 * Creates an instance of UsersProfileSetErrorSchema
 */
interface UsersProfileSetErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: Error96;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsersProfileSetErrorSchemaError extends ApiError<
  UsersProfileSetErrorSchema
> {}
