/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { UsersProfileGetErrorEnum } from '../models/usersProfileGetErrorEnum.js';

/**
 * Creates an instance of UsersProfileGetErrorSchema
 */
interface UsersProfileGetErrorSchema {
  /** Note: PHP callstack is only visible in dev/qa */
  callstack?: string;
  error: UsersProfileGetErrorEnum;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export class UsersProfileGetErrorSchemaError extends ApiError<
  UsersProfileGetErrorSchema
> {}
