/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AdminTeamsSettingsApi extends BaseApi {
  /**
   * Fetch information about settings in a workspace
   *
   * @param token        Authentication token. Requires scope: `admin.teams:read`
   * @param teamId
   * @return Response from the API call
   */
  async adminTeamsSettingsInfo(
    token: string,
    teamId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/admin.teams.settings.info');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('team_id', mapped.teamId);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Set the default channels of a workspace.
   *
   * @param token        Authentication token. Requires scope: `admin.teams:write`
   * @param teamId       ID for the workspace to set the default channel for.
   * @param channelIds   An array of channel IDs.
   * @return Response from the API call
   */
  async adminTeamsSettingsSetDefaultChannels(
    token: string,
    teamId: string,
    channelIds: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest(
      'POST',
      '/admin.teams.settings.setDefaultChannels'
    );
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      channelIds: [channelIds, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      token: mapped.token,
      team_id: mapped.teamId,
      channel_ids: mapped.channelIds,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Set the description of a given workspace.
   *
   * @param token        Authentication token. Requires scope: `admin.teams:write`
   * @param teamId       ID for the workspace to set the description for.
   * @param description  The new description for the workspace.
   * @return Response from the API call
   */
  async adminTeamsSettingsSetDescription(
    token: string,
    teamId: string,
    description: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest(
      'POST',
      '/admin.teams.settings.setDescription'
    );
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      description: [description, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ team_id: mapped.teamId, description: mapped.description });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * An API method that allows admins to set the discoverability of a given workspace
   *
   * @param token           Authentication token. Requires scope: `admin.teams:write`
   * @param teamId          The ID of the workspace to set discoverability on.
   * @param discoverability This workspace's discovery setting. It must be set to one of `open`,
   *                                  `invite_only`, `closed`, or `unlisted`.
   * @return Response from the API call
   */
  async adminTeamsSettingsSetDiscoverability(
    token: string,
    teamId: string,
    discoverability: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest(
      'POST',
      '/admin.teams.settings.setDiscoverability'
    );
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      discoverability: [discoverability, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      team_id: mapped.teamId,
      discoverability: mapped.discoverability,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Sets the icon of a workspace.
   *
   * @param token        Authentication token. Requires scope: `admin.teams:write`
   * @param imageUrl     Image URL for the icon
   * @param teamId       ID for the workspace to set the icon for.
   * @return Response from the API call
   */
  async adminTeamsSettingsSetIcon(
    token: string,
    imageUrl: string,
    teamId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.teams.settings.setIcon');
    const mapped = req.prepareArgs({
      token: [token, string()],
      imageUrl: [imageUrl, string()],
      teamId: [teamId, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      token: mapped.token,
      image_url: mapped.imageUrl,
      team_id: mapped.teamId,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Set the name of a given workspace.
   *
   * @param token        Authentication token. Requires scope: `admin.teams:write`
   * @param teamId       ID for the workspace to set the name for.
   * @param name         The new name of the workspace.
   * @return Response from the API call
   */
  async adminTeamsSettingsSetName(
    token: string,
    teamId: string,
    name: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.teams.settings.setName');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      name: [name, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ team_id: mapped.teamId, name: mapped.name });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
