/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AdminInviteRequestsDeniedApi extends BaseApi {
  /**
   * List all denied workspace invite requests.
   *
   * @param token        Authentication token. Requires scope: `admin.invites:read`
   * @param teamId       ID for the workspace where the invite requests were made.
   * @param cursor       Value of the `next_cursor` field sent as part of the previous api response
   * @param limit        The number of results that will be returned by the API on each invocation. Must be
   *                               between 1 - 1000 both inclusive
   * @return Response from the API call
   */
  async adminInviteRequestsDeniedList(
    token: string,
    teamId?: string,
    cursor?: string,
    limit?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/admin.inviteRequests.denied.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, optional(string())],
      cursor: [cursor, optional(string())],
      limit: [limit, optional(number())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('team_id', mapped.teamId);
    req.query('cursor', mapped.cursor);
    req.query('limit', mapped.limit);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
