/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AdminAppsApi extends BaseApi {
  /**
   * Approve an app for installation on a workspace.
   *
   * @param token        Authentication token. Requires scope: `admin.apps:write`
   * @param appId        The id of the app to approve.
   * @param requestId    The id of the request to approve.
   * @param teamId
   * @return Response from the API call
   */
  async adminAppsApprove(
    token: string,
    appId?: string,
    requestId?: string,
    teamId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.apps.approve');
    const mapped = req.prepareArgs({
      token: [token, string()],
      appId: [appId, optional(string())],
      requestId: [requestId, optional(string())],
      teamId: [teamId, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      app_id: mapped.appId,
      request_id: mapped.requestId,
      team_id: mapped.teamId,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Restrict an app for installation on a workspace.
   *
   * @param token        Authentication token. Requires scope: `admin.apps:write`
   * @param appId        The id of the app to restrict.
   * @param requestId    The id of the request to restrict.
   * @param teamId
   * @return Response from the API call
   */
  async adminAppsRestrict(
    token: string,
    appId?: string,
    requestId?: string,
    teamId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.apps.restrict');
    const mapped = req.prepareArgs({
      token: [token, string()],
      appId: [appId, optional(string())],
      requestId: [requestId, optional(string())],
      teamId: [teamId, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      app_id: mapped.appId,
      request_id: mapped.requestId,
      team_id: mapped.teamId,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
