/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AdminAppsRequestsApi extends BaseApi {
  /**
   * List app requests for a team/workspace.
   *
   * @param token        Authentication token. Requires scope: `admin.apps:read`
   * @param limit        The maximum number of items to return. Must be between 1 - 1000 both inclusive.
   * @param cursor       Set `cursor` to `next_cursor` returned by the previous call to list items in the
   *                               next page
   * @param teamId
   * @return Response from the API call
   */
  async adminAppsRequestsList(
    token: string,
    limit?: number,
    cursor?: string,
    teamId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/admin.apps.requests.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      limit: [limit, optional(number())],
      cursor: [cursor, optional(string())],
      teamId: [teamId, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('limit', mapped.limit);
    req.query('cursor', mapped.cursor);
    req.query('team_id', mapped.teamId);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
