/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AdminConversationsEkmApi extends BaseApi {
  /**
   * List all disconnected channels—i.e., channels that were once connected to other workspaces and then
   * disconnected—and the corresponding original channel IDs for key revocation with EKM.
   *
   * @param token        Authentication token. Requires scope: `admin.conversations:read`
   * @param channelIds   A comma-separated list of channels to filter to.
   * @param teamIds      A comma-separated list of the workspaces to which the channels you would like
   *                               returned belong.
   * @param limit        The maximum number of items to return. Must be between 1 - 1000 both inclusive.
   * @param cursor       Set `cursor` to `next_cursor` returned by the previous call to list items in the
   *                               next page.
   * @return Response from the API call
   */
  async adminConversationsEkmListOriginalConnectedChannelInfo(
    token: string,
    channelIds?: string,
    teamIds?: string,
    limit?: number,
    cursor?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest(
      'GET',
      '/admin.conversations.ekm.listOriginalConnectedChannelInfo'
    );
    const mapped = req.prepareArgs({
      token: [token, string()],
      channelIds: [channelIds, optional(string())],
      teamIds: [teamIds, optional(string())],
      limit: [limit, optional(number())],
      cursor: [cursor, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('channel_ids', mapped.channelIds);
    req.query('team_ids', mapped.teamIds);
    req.query('limit', mapped.limit);
    req.query('cursor', mapped.cursor);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
