/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AdminEmojiApi extends BaseApi {
  /**
   * Add an emoji.
   *
   * @param token        Authentication token. Requires scope: `admin.teams:write`
   * @param name         The name of the emoji to be removed. Colons (`:myemoji:`) around the value are not
   *                               required, although they may be included.
   * @param url          The URL of a file to use as an image for the emoji. Square images under 128KB and
   *                               with transparent backgrounds work best.
   * @return Response from the API call
   */
  async adminEmojiAdd(
    token: string,
    name: string,
    url: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.emoji.add');
    const mapped = req.prepareArgs({
      token: [token, string()],
      name: [name, string()],
      url: [url, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ token: mapped.token, name: mapped.name, url: mapped.url });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Add an emoji alias.
   *
   * @param token        Authentication token. Requires scope: `admin.teams:write`
   * @param name         The name of the emoji to be aliased. Colons (`:myemoji:`) around the value are not
   *                               required, although they may be included.
   * @param aliasFor     The alias of the emoji.
   * @return Response from the API call
   */
  async adminEmojiAddAlias(
    token: string,
    name: string,
    aliasFor: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.emoji.addAlias');
    const mapped = req.prepareArgs({
      token: [token, string()],
      name: [name, string()],
      aliasFor: [aliasFor, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      token: mapped.token,
      name: mapped.name,
      alias_for: mapped.aliasFor,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * List emoji for an Enterprise Grid organization.
   *
   * @param token        Authentication token. Requires scope: `admin.teams:read`
   * @param cursor       Set `cursor` to `next_cursor` returned by the previous call to list items in the
   *                               next page
   * @param limit        The maximum number of items to return. Must be between 1 - 1000 both inclusive.
   * @return Response from the API call
   */
  async adminEmojiList(
    token: string,
    cursor?: string,
    limit?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/admin.emoji.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      cursor: [cursor, optional(string())],
      limit: [limit, optional(number())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('cursor', mapped.cursor);
    req.query('limit', mapped.limit);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Remove an emoji across an Enterprise Grid organization
   *
   * @param token        Authentication token. Requires scope: `admin.teams:write`
   * @param name         The name of the emoji to be removed. Colons (`:myemoji:`) around the value are not
   *                               required, although they may be included.
   * @return Response from the API call
   */
  async adminEmojiRemove(
    token: string,
    name: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.emoji.remove');
    const mapped = req.prepareArgs({
      token: [token, string()],
      name: [name, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ token: mapped.token, name: mapped.name });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Rename an emoji.
   *
   * @param token        Authentication token. Requires scope: `admin.teams:write`
   * @param name         The name of the emoji to be renamed. Colons (`:myemoji:`) around the value are not
   *                               required, although they may be included.
   * @param newName      The new name of the emoji.
   * @return Response from the API call
   */
  async adminEmojiRename(
    token: string,
    name: string,
    newName: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.emoji.rename');
    const mapped = req.prepareArgs({
      token: [token, string()],
      name: [name, string()],
      newName: [newName, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      token: mapped.token,
      name: mapped.name,
      new_name: mapped.newName,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
