/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AdminConversationsRestrictAccessApi extends BaseApi {
  /**
   * Add an allowlist of IDP groups for accessing a channel
   *
   * @param token        Authentication token. Requires scope: `admin.conversations:write`
   * @param groupId      The [IDP Group](https://slack.com/help/articles/115001435788-Connect-identity-
   *                               provider-groups-to-your-Enterprise-Grid-org) ID to be an allowlist for the private
   *                               channel.
   * @param channelId    The channel to link this group to.
   * @param teamId       The workspace where the channel exists. This argument is required for channels only
   *                               tied to one workspace, and optional for channels that are shared across an
   *                               organization.
   * @return Response from the API call
   */
  async adminConversationsRestrictAccessAddGroup(
    token: string,
    groupId: string,
    channelId: string,
    teamId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest(
      'POST',
      '/admin.conversations.restrictAccess.addGroup'
    );
    const mapped = req.prepareArgs({
      token: [token, string()],
      groupId: [groupId, string()],
      channelId: [channelId, string()],
      teamId: [teamId, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      token: mapped.token,
      group_id: mapped.groupId,
      channel_id: mapped.channelId,
      team_id: mapped.teamId,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * List all IDP Groups linked to a channel
   *
   * @param token        Authentication token. Requires scope: `admin.conversations:read`
   * @param channelId
   * @param teamId       The workspace where the channel exists. This argument is required for channels only
   *                               tied to one workspace, and optional for channels that are shared across an
   *                               organization.
   * @return Response from the API call
   */
  async adminConversationsRestrictAccessListGroups(
    token: string,
    channelId: string,
    teamId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest(
      'GET',
      '/admin.conversations.restrictAccess.listGroups'
    );
    const mapped = req.prepareArgs({
      token: [token, string()],
      channelId: [channelId, string()],
      teamId: [teamId, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('channel_id', mapped.channelId);
    req.query('team_id', mapped.teamId);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Remove a linked IDP group linked from a private channel
   *
   * @param token        Authentication token. Requires scope: `admin.conversations:write`
   * @param teamId       The workspace where the channel exists. This argument is required for channels only
   *                               tied to one workspace, and optional for channels that are shared across an
   *                               organization.
   * @param groupId      The [IDP Group](https://slack.com/help/articles/115001435788-Connect-identity-
   *                               provider-groups-to-your-Enterprise-Grid-org) ID to remove from the private channel.
   * @param channelId    The channel to remove the linked group from.
   * @return Response from the API call
   */
  async adminConversationsRestrictAccessRemoveGroup(
    token: string,
    teamId: string,
    groupId: string,
    channelId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest(
      'POST',
      '/admin.conversations.restrictAccess.removeGroup'
    );
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      groupId: [groupId, string()],
      channelId: [channelId, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      token: mapped.token,
      team_id: mapped.teamId,
      group_id: mapped.groupId,
      channel_id: mapped.channelId,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
