/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { boolean, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AdminUsersApi extends BaseApi {
  /**
   * Add an Enterprise user to a workspace.
   *
   * @param token               Authentication token. Requires scope: `admin.users:write`
   * @param teamId              The ID (`T1234`) of the workspace.
   * @param userId              The ID of the user to add to the workspace.
   * @param isRestricted        True if user should be added to the workspace as a guest.
   * @param isUltraRestricted   True if user should be added to the workspace as a single-channel guest.
   * @param channelIds          Comma separated values of channel IDs to add user in the new workspace.
   * @return Response from the API call
   */
  async adminUsersAssign(
    token: string,
    teamId: string,
    userId: string,
    isRestricted?: boolean,
    isUltraRestricted?: boolean,
    channelIds?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.users.assign');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      userId: [userId, string()],
      isRestricted: [isRestricted, optional(boolean())],
      isUltraRestricted: [isUltraRestricted, optional(boolean())],
      channelIds: [channelIds, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      team_id: mapped.teamId,
      user_id: mapped.userId,
      is_restricted: mapped.isRestricted,
      is_ultra_restricted: mapped.isUltraRestricted,
      channel_ids: mapped.channelIds,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Invite a user to a workspace.
   *
   * @param token               Authentication token. Requires scope: `admin.users:write`
   * @param teamId              The ID (`T1234`) of the workspace.
   * @param email               The email address of the person to invite.
   * @param channelIds          A comma-separated list of `channel_id`s for this user to join. At least one
   *                                       channel is required.
   * @param customMessage       An optional message to send to the user in the invite email.
   * @param realName            Full name of the user.
   * @param resend              Allow this invite to be resent in the future if a user has not signed up
   *                                       yet. (default: false)
   * @param isRestricted        Is this user a multi-channel guest user? (default: false)
   * @param isUltraRestricted   Is this user a single channel guest user? (default: false)
   * @param guestExpirationTs   Timestamp when guest account should be disabled. Only include this
   *                                       timestamp if you are inviting a guest user and you want their account to
   *                                       expire on a certain date.
   * @return Response from the API call
   */
  async adminUsersInvite(
    token: string,
    teamId: string,
    email: string,
    channelIds: string,
    customMessage?: string,
    realName?: string,
    resend?: boolean,
    isRestricted?: boolean,
    isUltraRestricted?: boolean,
    guestExpirationTs?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.users.invite');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      email: [email, string()],
      channelIds: [channelIds, string()],
      customMessage: [customMessage, optional(string())],
      realName: [realName, optional(string())],
      resend: [resend, optional(boolean())],
      isRestricted: [isRestricted, optional(boolean())],
      isUltraRestricted: [isUltraRestricted, optional(boolean())],
      guestExpirationTs: [guestExpirationTs, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      team_id: mapped.teamId,
      email: mapped.email,
      channel_ids: mapped.channelIds,
      custom_message: mapped.customMessage,
      real_name: mapped.realName,
      resend: mapped.resend,
      is_restricted: mapped.isRestricted,
      is_ultra_restricted: mapped.isUltraRestricted,
      guest_expiration_ts: mapped.guestExpirationTs,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * List users on a workspace
   *
   * @param token        Authentication token. Requires scope: `admin.users:read`
   * @param teamId       The ID (`T1234`) of the workspace.
   * @param cursor       Set `cursor` to `next_cursor` returned by the previous call to list items in the
   *                               next page.
   * @param limit        Limit for how many users to be retrieved per page
   * @return Response from the API call
   */
  async adminUsersList(
    token: string,
    teamId: string,
    cursor?: string,
    limit?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/admin.users.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      cursor: [cursor, optional(string())],
      limit: [limit, optional(number())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('team_id', mapped.teamId);
    req.query('cursor', mapped.cursor);
    req.query('limit', mapped.limit);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Remove a user from a workspace.
   *
   * @param token        Authentication token. Requires scope: `admin.users:write`
   * @param teamId       The ID (`T1234`) of the workspace.
   * @param userId       The ID of the user to remove.
   * @return Response from the API call
   */
  async adminUsersRemove(
    token: string,
    teamId: string,
    userId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.users.remove');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      userId: [userId, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ team_id: mapped.teamId, user_id: mapped.userId });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Set an existing guest, regular user, or owner to be an admin user.
   *
   * @param token        Authentication token. Requires scope: `admin.users:write`
   * @param teamId       The ID (`T1234`) of the workspace.
   * @param userId       The ID of the user to designate as an admin.
   * @return Response from the API call
   */
  async adminUsersSetAdmin(
    token: string,
    teamId: string,
    userId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.users.setAdmin');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      userId: [userId, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ team_id: mapped.teamId, user_id: mapped.userId });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Set an expiration for a guest user
   *
   * @param token         Authentication token. Requires scope: `admin.users:write`
   * @param teamId        The ID (`T1234`) of the workspace.
   * @param userId        The ID of the user to set an expiration for.
   * @param expirationTs  Timestamp when guest account should be disabled.
   * @return Response from the API call
   */
  async adminUsersSetExpiration(
    token: string,
    teamId: string,
    userId: string,
    expirationTs: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.users.setExpiration');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      userId: [userId, string()],
      expirationTs: [expirationTs, number()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      team_id: mapped.teamId,
      user_id: mapped.userId,
      expiration_ts: mapped.expirationTs,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Set an existing guest, regular user, or admin user to be a workspace owner.
   *
   * @param token        Authentication token. Requires scope: `admin.users:write`
   * @param teamId       The ID (`T1234`) of the workspace.
   * @param userId       Id of the user to promote to owner.
   * @return Response from the API call
   */
  async adminUsersSetOwner(
    token: string,
    teamId: string,
    userId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.users.setOwner');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      userId: [userId, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ team_id: mapped.teamId, user_id: mapped.userId });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Set an existing guest user, admin user, or owner to be a regular user.
   *
   * @param token        Authentication token. Requires scope: `admin.users:write`
   * @param teamId       The ID (`T1234`) of the workspace.
   * @param userId       The ID of the user to designate as a regular user.
   * @return Response from the API call
   */
  async adminUsersSetRegular(
    token: string,
    teamId: string,
    userId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.users.setRegular');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      userId: [userId, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ team_id: mapped.teamId, user_id: mapped.userId });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
