/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { boolean, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AdminUsersSessionApi extends BaseApi {
  /**
   * Invalidate a single session for a user by session_id
   *
   * @param token        Authentication token. Requires scope: `admin.users:write`
   * @param teamId       ID of the team that the session belongs to
   * @param sessionId
   * @return Response from the API call
   */
  async adminUsersSessionInvalidate(
    token: string,
    teamId: string,
    sessionId: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.users.session.invalidate');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamId: [teamId, string()],
      sessionId: [sessionId, number()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ team_id: mapped.teamId, session_id: mapped.sessionId });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Wipes all valid sessions on all devices for a given user
   *
   * @param token        Authentication token. Requires scope: `admin.users:write`
   * @param userId       The ID of the user to wipe sessions for
   * @param mobileOnly   Only expire mobile sessions (default: false)
   * @param webOnly      Only expire web sessions (default: false)
   * @return Response from the API call
   */
  async adminUsersSessionReset(
    token: string,
    userId: string,
    mobileOnly?: boolean,
    webOnly?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.users.session.reset');
    const mapped = req.prepareArgs({
      token: [token, string()],
      userId: [userId, string()],
      mobileOnly: [mobileOnly, optional(boolean())],
      webOnly: [webOnly, optional(boolean())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      user_id: mapped.userId,
      mobile_only: mapped.mobileOnly,
      web_only: mapped.webOnly,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
