/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AdminTeamsApi extends BaseApi {
  /**
   * Create an Enterprise team.
   *
   * @param token                Authentication token. Requires scope: `admin.teams:write`
   * @param teamDomain           Team domain (for example, slacksoftballteam).
   * @param teamName             Team name (for example, Slack Softball Team).
   * @param teamDescription      Description for the team.
   * @param teamDiscoverability  Who can join the team. A team's discoverability can be `open`, `closed`,
   *                                       `invite_only`, or `unlisted`.
   * @return Response from the API call
   */
  async adminTeamsCreate(
    token: string,
    teamDomain: string,
    teamName: string,
    teamDescription?: string,
    teamDiscoverability?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.teams.create');
    const mapped = req.prepareArgs({
      token: [token, string()],
      teamDomain: [teamDomain, string()],
      teamName: [teamName, string()],
      teamDescription: [teamDescription, optional(string())],
      teamDiscoverability: [teamDiscoverability, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      team_domain: mapped.teamDomain,
      team_name: mapped.teamName,
      team_description: mapped.teamDescription,
      team_discoverability: mapped.teamDiscoverability,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * List all teams on an Enterprise organization
   *
   * @param token        Authentication token. Requires scope: `admin.teams:read`
   * @param limit        The maximum number of items to return. Must be between 1 - 100 both inclusive.
   * @param cursor       Set `cursor` to `next_cursor` returned by the previous call to list items in the
   *                               next page.
   * @return Response from the API call
   */
  async adminTeamsList(
    token: string,
    limit?: number,
    cursor?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/admin.teams.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      limit: [limit, optional(number())],
      cursor: [cursor, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('limit', mapped.limit);
    req.query('cursor', mapped.cursor);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
