/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AdminUsergroupsApi extends BaseApi {
  /**
   * Add one or more default channels to an IDP group.
   *
   * @param token        Authentication token. Requires scope: `admin.usergroups:write`
   * @param usergroupId  ID of the IDP group to add default channels for.
   * @param channelIds   Comma separated string of channel IDs.
   * @param teamId       The workspace to add default channels in.
   * @return Response from the API call
   */
  async adminUsergroupsAddChannels(
    token: string,
    usergroupId: string,
    channelIds: string,
    teamId?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.usergroups.addChannels');
    const mapped = req.prepareArgs({
      token: [token, string()],
      usergroupId: [usergroupId, string()],
      channelIds: [channelIds, string()],
      teamId: [teamId, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      usergroup_id: mapped.usergroupId,
      channel_ids: mapped.channelIds,
      team_id: mapped.teamId,
    });
    req.defaultToError(
      DefaultErrorTemplateError,
      'Typical error response if the token provided is not associated with an Org Admin or Owner'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Associate one or more default workspaces with an organization-wide IDP group.
   *
   * @param token          Authentication token. Requires scope: `admin.teams:write`
   * @param usergroupId    An encoded usergroup (IDP Group) ID.
   * @param teamIds        A comma separated list of encoded team (workspace) IDs. Each workspace *MUST*
   *                                  belong to the organization associated with the token.
   * @param autoProvision  When `true`, this method automatically creates new workspace accounts for the
   *                                  IDP group members.
   * @return Response from the API call
   */
  async adminUsergroupsAddTeams(
    token: string,
    usergroupId: string,
    teamIds: string,
    autoProvision?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.usergroups.addTeams');
    const mapped = req.prepareArgs({
      token: [token, string()],
      usergroupId: [usergroupId, string()],
      teamIds: [teamIds, string()],
      autoProvision: [autoProvision, optional(boolean())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      usergroup_id: mapped.usergroupId,
      team_ids: mapped.teamIds,
      auto_provision: mapped.autoProvision,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * List the channels linked to an org-level IDP group (user group).
   *
   * @param token               Authentication token. Requires scope: `admin.usergroups:read`
   * @param usergroupId         ID of the IDP group to list default channels for.
   * @param teamId              ID of the the workspace.
   * @param includeNumMembers   Flag to include or exclude the count of members per channel.
   * @return Response from the API call
   */
  async adminUsergroupsListChannels(
    token: string,
    usergroupId: string,
    teamId?: string,
    includeNumMembers?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/admin.usergroups.listChannels');
    const mapped = req.prepareArgs({
      token: [token, string()],
      usergroupId: [usergroupId, string()],
      teamId: [teamId, optional(string())],
      includeNumMembers: [includeNumMembers, optional(boolean())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('usergroup_id', mapped.usergroupId);
    req.query('team_id', mapped.teamId);
    req.query('include_num_members', mapped.includeNumMembers);
    req.defaultToError(
      DefaultErrorTemplateError,
      'Typical error response if the token provided is not associated with an Org Admin or Owner'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Remove one or more default channels from an org-level IDP group (user group).
   *
   * @param token        Authentication token. Requires scope: `admin.usergroups:write`
   * @param usergroupId  ID of the IDP Group
   * @param channelIds   Comma-separated string of channel IDs
   * @return Response from the API call
   */
  async adminUsergroupsRemoveChannels(
    token: string,
    usergroupId: string,
    channelIds: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/admin.usergroups.removeChannels');
    const mapped = req.prepareArgs({
      token: [token, string()],
      usergroupId: [usergroupId, string()],
      channelIds: [channelIds, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      usergroup_id: mapped.usergroupId,
      channel_ids: mapped.channelIds,
    });
    req.defaultToError(
      DefaultErrorTemplateError,
      'Typical error response if the token provided is not associated with an Org Admin or Owner'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
