/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ApiTestSuccessSchema,
  apiTestSuccessSchemaSchema,
} from '../models/apiTestSuccessSchema.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiTestErrorSchemaError } from '../errors/apiTestErrorSchemaError.js';

export class Api extends BaseApi {
  /**
   * Checks API calling code.
   *
   * @param error        Error response to return
   * @param foo          example property to return
   * @return Response from the API call
   */
  async apiTest(
    error?: string,
    foo?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ApiTestSuccessSchema>> {
    const req = this.createRequest('GET', '/api.test');
    const mapped = req.prepareArgs({
      error: [error, optional(string())],
      foo: [foo, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('error', mapped.error);
    req.query('foo', mapped.foo);
    req.defaultToError(ApiTestErrorSchemaError, 'Artificial error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(apiTestSuccessSchemaSchema, requestOptions);
  }
}
