/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AppsPermissionsUsersApi extends BaseApi {
  /**
   * Returns list of user grants and corresponding scopes this app has on a team.
   *
   * @param token        Authentication token. Requires scope: `none`
   * @param cursor       Paginate through collections of data by setting the `cursor` parameter to a
   *                               `next_cursor` attribute returned by a previous request's `response_metadata`.
   *                               Default value fetches the first "page" of the collection. See
   *                               [pagination](/docs/pagination) for more detail.
   * @param limit        The maximum number of items to return.
   * @return Response from the API call
   */
  async appsPermissionsUsersList(
    token: string,
    cursor?: string,
    limit?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/apps.permissions.users.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      cursor: [cursor, optional(string())],
      limit: [limit, optional(number())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('cursor', mapped.cursor);
    req.query('limit', mapped.limit);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Enables an app to trigger a permissions modal to grant an app access to a user access scope.
   *
   * @param token        Authentication token. Requires scope: `none`
   * @param scopes       A comma separated list of user scopes to request for
   * @param triggerId    Token used to trigger the request
   * @param user         The user this scope is being requested for
   * @return Response from the API call
   */
  async appsPermissionsUsersRequest(
    token: string,
    scopes: string,
    triggerId: string,
    user: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/apps.permissions.users.request');
    const mapped = req.prepareArgs({
      token: [token, string()],
      scopes: [scopes, string()],
      triggerId: [triggerId, string()],
      user: [user, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('scopes', mapped.scopes);
    req.query('trigger_id', mapped.triggerId);
    req.query('user', mapped.user);
    req.defaultToError(
      DefaultErrorTemplateError,
      'Standard failure response when trigger_id is invalid'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
