/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ApiPermissionsScopesListSuccessSchema,
  apiPermissionsScopesListSuccessSchemaSchema,
} from '../models/apiPermissionsScopesListSuccessSchema.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { AppsPermissionsScopesListErrorSchemaError } from '../errors/appsPermissionsScopesListErrorSchemaError.js';

export class AppsPermissionsScopesApi extends BaseApi {
  /**
   * Returns list of scopes this app has on a team.
   *
   * @param token        Authentication token. Requires scope: `none`
   * @return Response from the API call
   */
  async appsPermissionsScopesList(
    token: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ApiPermissionsScopesListSuccessSchema>> {
    const req = this.createRequest('GET', '/apps.permissions.scopes.list');
    const mapped = req.prepareArgs({ token: [token, string()] });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.defaultToError(
      AppsPermissionsScopesListErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(
      apiPermissionsScopesListSuccessSchemaSchema,
      requestOptions
    );
  }
}
