/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class AppsEventAuthorizationsApi extends BaseApi {
  /**
   * Get a list of authorizations for the given event context. Each authorization represents an app
   * installation that the event is visible to.
   *
   * @param token         Authentication token. Requires scope: `authorizations:read`
   * @param eventContext
   * @param cursor
   * @param limit
   * @return Response from the API call
   */
  async appsEventAuthorizationsList(
    token: string,
    eventContext: string,
    cursor?: string,
    limit?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/apps.event.authorizations.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      eventContext: [eventContext, string()],
      cursor: [cursor, optional(string())],
      limit: [limit, optional(number())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('event_context', mapped.eventContext);
    req.query('cursor', mapped.cursor);
    req.query('limit', mapped.limit);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
