/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AppsPermissionsInfoSchema,
  appsPermissionsInfoSchemaSchema,
} from '../models/appsPermissionsInfoSchema.js';
import {
  AppsPermissionsRequestSchema,
  appsPermissionsRequestSchemaSchema,
} from '../models/appsPermissionsRequestSchema.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { AppsPermissionsInfoErrorSchemaError } from '../errors/appsPermissionsInfoErrorSchemaError.js';
import { AppsPermissionsRequestErrorSchemaError } from '../errors/appsPermissionsRequestErrorSchemaError.js';

export class AppsPermissionsApi extends BaseApi {
  /**
   * Returns list of permissions this app has on a team.
   *
   * @param token        Authentication token. Requires scope: `none`
   * @return Response from the API call
   */
  async appsPermissionsInfo(
    token?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AppsPermissionsInfoSchema>> {
    const req = this.createRequest('GET', '/apps.permissions.info');
    const mapped = req.prepareArgs({ token: [token, optional(string())] });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.defaultToError(
      AppsPermissionsInfoErrorSchemaError,
      'Standard failure response when used with an invalid token'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(appsPermissionsInfoSchemaSchema, requestOptions);
  }

  /**
   * Allows an app to request additional scopes
   *
   * @param token        Authentication token. Requires scope: `none`
   * @param scopes       A comma separated list of scopes to request for
   * @param triggerId    Token used to trigger the permissions API
   * @return Response from the API call
   */
  async appsPermissionsRequest(
    token: string,
    scopes: string,
    triggerId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AppsPermissionsRequestSchema>> {
    const req = this.createRequest('GET', '/apps.permissions.request');
    const mapped = req.prepareArgs({
      token: [token, string()],
      scopes: [scopes, string()],
      triggerId: [triggerId, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('scopes', mapped.scopes);
    req.query('trigger_id', mapped.triggerId);
    req.defaultToError(
      AppsPermissionsRequestErrorSchemaError,
      'Standard failure response when trigger_id is invalid'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(appsPermissionsRequestSchemaSchema, requestOptions);
  }
}
