/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AppsPermissionsResourcesListSuccessSchema,
  appsPermissionsResourcesListSuccessSchemaSchema,
} from '../models/appsPermissionsResourcesListSuccessSchema.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { AppsPermissionsResourcesListErrorSchemaError } from '../errors/appsPermissionsResourcesListErrorSchemaError.js';

export class AppsPermissionsResourcesApi extends BaseApi {
  /**
   * Returns list of resource grants this app has on a team.
   *
   * @param token        Authentication token. Requires scope: `none`
   * @param cursor       Paginate through collections of data by setting the `cursor` parameter to a
   *                               `next_cursor` attribute returned by a previous request's `response_metadata`.
   *                               Default value fetches the first "page" of the collection.
   * @param limit        The maximum number of items to return.
   * @return Response from the API call
   */
  async appsPermissionsResourcesList(
    token: string,
    cursor?: string,
    limit?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AppsPermissionsResourcesListSuccessSchema>> {
    const req = this.createRequest('GET', '/apps.permissions.resources.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      cursor: [cursor, optional(string())],
      limit: [limit, optional(number())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('cursor', mapped.cursor);
    req.query('limit', mapped.limit);
    req.defaultToError(
      AppsPermissionsResourcesListErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(
      appsPermissionsResourcesListSuccessSchemaSchema,
      requestOptions
    );
  }
}
