/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class CallsApi extends BaseApi {
  /**
   * Registers a new Call.
   *
   * @param token                Authentication token. Requires scope: `calls:write`
   * @param externalUniqueId     An ID supplied by the 3rd-party Call provider. It must be unique across all
   *                                       Calls from that service.
   * @param joinUrl              The URL required for a client to join the Call.
   * @param externalDisplayId    An optional, human-readable ID supplied by the 3rd-party Call provider. If
   *                                       supplied, this ID will be displayed in the Call object.
   * @param desktopAppJoinUrl    When supplied, available Slack clients will attempt to directly launch the
   *                                       3rd-party Call with this URL.
   * @param dateStart            Call start time in UTC UNIX timestamp format
   * @param title                The name of the Call.
   * @param createdBy            The valid Slack user ID of the user who created this Call. When this method
   *                                       is called with a user token, the `created_by` field is optional and defaults
   *                                       to the authed user of the token. Otherwise, the field is required.
   * @param users                The list of users to register as participants in the Call. [Read more on
   *                                       how to specify users here](/apis/calls#users).
   * @return Response from the API call
   */
  async callsAdd(
    token: string,
    externalUniqueId: string,
    joinUrl: string,
    externalDisplayId?: string,
    desktopAppJoinUrl?: string,
    dateStart?: number,
    title?: string,
    createdBy?: string,
    users?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/calls.add');
    const mapped = req.prepareArgs({
      token: [token, string()],
      externalUniqueId: [externalUniqueId, string()],
      joinUrl: [joinUrl, string()],
      externalDisplayId: [externalDisplayId, optional(string())],
      desktopAppJoinUrl: [desktopAppJoinUrl, optional(string())],
      dateStart: [dateStart, optional(number())],
      title: [title, optional(string())],
      createdBy: [createdBy, optional(string())],
      users: [users, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      external_unique_id: mapped.externalUniqueId,
      join_url: mapped.joinUrl,
      external_display_id: mapped.externalDisplayId,
      desktop_app_join_url: mapped.desktopAppJoinUrl,
      date_start: mapped.dateStart,
      title: mapped.title,
      created_by: mapped.createdBy,
      users: mapped.users,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Ends a Call.
   *
   * @param token        Authentication token. Requires scope: `calls:write`
   * @param id           `id` returned when registering the call using the [`calls.add`](/methods/calls.add)
   *                               method.
   * @param duration     Call duration in seconds
   * @return Response from the API call
   */
  async callsEnd(
    token: string,
    id: string,
    duration?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/calls.end');
    const mapped = req.prepareArgs({
      token: [token, string()],
      id: [id, string()],
      duration: [duration, optional(number())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ id: mapped.id, duration: mapped.duration });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Returns information about a Call.
   *
   * @param token        Authentication token. Requires scope: `calls:read`
   * @param id           `id` of the Call returned by the [`calls.add`](/methods/calls.add) method.
   * @return Response from the API call
   */
  async callsInfo(
    token: string,
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/calls.info');
    const mapped = req.prepareArgs({
      token: [token, string()],
      id: [id, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('id', mapped.id);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Updates information about a Call.
   *
   * @param token                Authentication token. Requires scope: `calls:write`
   * @param id                   `id` returned by the [`calls.add`](/methods/calls.add) method.
   * @param title                The name of the Call.
   * @param joinUrl              The URL required for a client to join the Call.
   * @param desktopAppJoinUrl    When supplied, available Slack clients will attempt to directly launch the
   *                                       3rd-party Call with this URL.
   * @return Response from the API call
   */
  async callsUpdate(
    token: string,
    id: string,
    title?: string,
    joinUrl?: string,
    desktopAppJoinUrl?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/calls.update');
    const mapped = req.prepareArgs({
      token: [token, string()],
      id: [id, string()],
      title: [title, optional(string())],
      joinUrl: [joinUrl, optional(string())],
      desktopAppJoinUrl: [desktopAppJoinUrl, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      id: mapped.id,
      title: mapped.title,
      join_url: mapped.joinUrl,
      desktop_app_join_url: mapped.desktopAppJoinUrl,
    });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
