/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class CallsParticipantsApi extends BaseApi {
  /**
   * Registers new participants added to a Call.
   *
   * @param token        Authentication token. Requires scope: `calls:write`
   * @param id           `id` returned by the [`calls.add`](/methods/calls.add) method.
   * @param users        The list of users to add as participants in the Call. [Read more on how to specify
   *                               users here](/apis/calls#users).
   * @return Response from the API call
   */
  async callsParticipantsAdd(
    token: string,
    id: string,
    users: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/calls.participants.add');
    const mapped = req.prepareArgs({
      token: [token, string()],
      id: [id, string()],
      users: [users, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ id: mapped.id, users: mapped.users });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Registers participants removed from a Call.
   *
   * @param token        Authentication token. Requires scope: `calls:write`
   * @param id           `id` returned by the [`calls.add`](/methods/calls.add) method.
   * @param users        The list of users to remove as participants in the Call. [Read more on how to
   *                               specify users here](/apis/calls#users).
   * @return Response from the API call
   */
  async callsParticipantsRemove(
    token: string,
    id: string,
    users: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('POST', '/calls.participants.remove');
    const mapped = req.prepareArgs({
      token: [token, string()],
      id: [id, string()],
      users: [users, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ id: mapped.id, users: mapped.users });
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
