/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DialogOpenSchema,
  dialogOpenSchemaSchema,
} from '../models/dialogOpenSchema.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DialogOpenErrorSchemaError } from '../errors/dialogOpenErrorSchemaError.js';

export class DialogApi extends BaseApi {
  /**
   * Open a dialog with a user
   *
   * @param token        Authentication token. Requires scope: `none`
   * @param dialog       The dialog definition. This must be a JSON-encoded string.
   * @param triggerId    Exchange a trigger to post to the user.
   * @return Response from the API call
   */
  async dialogOpen(
    token: string,
    dialog: string,
    triggerId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DialogOpenSchema>> {
    const req = this.createRequest('GET', '/dialog.open');
    const mapped = req.prepareArgs({
      token: [token, string()],
      dialog: [dialog, string()],
      triggerId: [triggerId, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('dialog', mapped.dialog);
    req.query('trigger_id', mapped.triggerId);
    req.defaultToError(
      DialogOpenErrorSchemaError,
      'Typical error response, before getting to any possible validation errors.'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(dialogOpenSchemaSchema, requestOptions);
  }
}
