/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import {
  DndEndDndSchema,
  dndEndDndSchemaSchema,
} from '../models/dndEndDndSchema.js';
import {
  DndEndSnoozeSchema,
  dndEndSnoozeSchemaSchema,
} from '../models/dndEndSnoozeSchema.js';
import { DndInfoSchema, dndInfoSchemaSchema } from '../models/dndInfoSchema.js';
import {
  DndSetSnoozeSchema,
  dndSetSnoozeSchemaSchema,
} from '../models/dndSetSnoozeSchema.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';
import { DndEndDndErrorSchemaError } from '../errors/dndEndDndErrorSchemaError.js';
import { DndEndSnoozeErrorSchemaError } from '../errors/dndEndSnoozeErrorSchemaError.js';
import { DndInfoErrorSchemaError } from '../errors/dndInfoErrorSchemaError.js';
import { DndSetSnoozeErrorSchemaError } from '../errors/dndSetSnoozeErrorSchemaError.js';

export class DndApi extends BaseApi {
  /**
   * Ends the current user's Do Not Disturb session immediately.
   *
   * @param token        Authentication token. Requires scope: `dnd:write`
   * @return Response from the API call
   */
  async dndEndDnd(
    token: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DndEndDndSchema>> {
    const req = this.createRequest('POST', '/dnd.endDnd');
    const mapped = req.prepareArgs({ token: [token, string()] });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.defaultToError(DndEndDndErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(dndEndDndSchemaSchema, requestOptions);
  }

  /**
   * Ends the current user's snooze mode immediately.
   *
   * @param token        Authentication token. Requires scope: `dnd:write`
   * @return Response from the API call
   */
  async dndEndSnooze(
    token: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DndEndSnoozeSchema>> {
    const req = this.createRequest('POST', '/dnd.endSnooze');
    const mapped = req.prepareArgs({ token: [token, string()] });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.defaultToError(DndEndSnoozeErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(dndEndSnoozeSchemaSchema, requestOptions);
  }

  /**
   * Retrieves a user's current Do Not Disturb status.
   *
   * @param token        Authentication token. Requires scope: `dnd:read`
   * @param user         User to fetch status for (defaults to current user)
   * @return Response from the API call
   */
  async dndInfo(
    token?: string,
    user?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DndInfoSchema>> {
    const req = this.createRequest('GET', '/dnd.info');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      user: [user, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('user', mapped.user);
    req.defaultToError(DndInfoErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(dndInfoSchemaSchema, requestOptions);
  }

  /**
   * Turns on Do Not Disturb mode for the current user, or changes its duration.
   *
   * @param token        Authentication token. Requires scope: `dnd:write`
   * @param numMinutes   Number of minutes, from now, to snooze until.
   * @return Response from the API call
   */
  async dndSetSnooze(
    token: string,
    numMinutes: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DndSetSnoozeSchema>> {
    const req = this.createRequest('POST', '/dnd.setSnooze');
    const mapped = req.prepareArgs({
      token: [token, string()],
      numMinutes: [numMinutes, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ token: mapped.token, num_minutes: mapped.numMinutes });
    req.defaultToError(DndSetSnoozeErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(dndSetSnoozeSchemaSchema, requestOptions);
  }

  /**
   * Retrieves the Do Not Disturb status for up to 50 users on a team.
   *
   * @param token        Authentication token. Requires scope: `dnd:read`
   * @param users        Comma-separated list of users to fetch Do Not Disturb status for
   * @return Response from the API call
   */
  async dndTeamInfo(
    token?: string,
    users?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/dnd.teamInfo');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      users: [users, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('users', mapped.users);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
