/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class EmojiApi extends BaseApi {
  /**
   * Lists custom emoji for a team.
   *
   * @param token        Authentication token. Requires scope: `emoji:read`
   * @return Response from the API call
   */
  async emojiList(
    token: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/emoji.list');
    const mapped = req.prepareArgs({ token: [token, string()] });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
