/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  FilesCommentsDeleteSchema,
  filesCommentsDeleteSchemaSchema,
} from '../models/filesCommentsDeleteSchema.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { FilesCommentsDeleteErrorSchemaError } from '../errors/filesCommentsDeleteErrorSchemaError.js';

export class FilesCommentsApi extends BaseApi {
  /**
   * Deletes an existing comment on a file.
   *
   * @param token        Authentication token. Requires scope: `files:write:user`
   * @param file         File to delete a comment from.
   * @param id           The comment to delete.
   * @return Response from the API call
   */
  async filesCommentsDelete(
    token?: string,
    file?: string,
    id?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FilesCommentsDeleteSchema>> {
    const req = this.createRequest('POST', '/files.comments.delete');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      file: [file, optional(string())],
      id: [id, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.header('token', mapped.token);
    req.form({ file: mapped.file, id: mapped.id });
    req.defaultToError(
      FilesCommentsDeleteErrorSchemaError,
      'Standard failure response when used with an invalid token'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(filesCommentsDeleteSchemaSchema, requestOptions);
  }
}
