/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  FilesDeleteSchema,
  filesDeleteSchemaSchema,
} from '../models/filesDeleteSchema.js';
import {
  FilesInfoSchema,
  filesInfoSchemaSchema,
} from '../models/filesInfoSchema.js';
import {
  FilesListSchema,
  filesListSchemaSchema,
} from '../models/filesListSchema.js';
import {
  FilesRevokePublicUrlSchema,
  filesRevokePublicUrlSchemaSchema,
} from '../models/filesRevokePublicUrlSchema.js';
import {
  FilesSharedPublicUrlSchema,
  filesSharedPublicUrlSchemaSchema,
} from '../models/filesSharedPublicUrlSchema.js';
import {
  FilesUploadSchema,
  filesUploadSchemaSchema,
} from '../models/filesUploadSchema.js';
import { boolean, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { FilesDeleteErrorSchemaError } from '../errors/filesDeleteErrorSchemaError.js';
import { FilesInfoErrorSchemaError } from '../errors/filesInfoErrorSchemaError.js';
import { FilesListErrorSchemaError } from '../errors/filesListErrorSchemaError.js';
import { FilesRevokePublicUrlErrorSchemaError } from '../errors/filesRevokePublicUrlErrorSchemaError.js';
import { FilesSharedPublicUrlErrorSchemaError } from '../errors/filesSharedPublicUrlErrorSchemaError.js';
import { FilesUploadErrorSchemaError } from '../errors/filesUploadErrorSchemaError.js';

export class FilesApi extends BaseApi {
  /**
   * Deletes a file.
   *
   * @param token        Authentication token. Requires scope: `files:write:user`
   * @param file         ID of file to delete.
   * @return Response from the API call
   */
  async filesDelete(
    token?: string,
    file?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FilesDeleteSchema>> {
    const req = this.createRequest('POST', '/files.delete');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      file: [file, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.header('token', mapped.token);
    req.form({ file: mapped.file });
    req.defaultToError(FilesDeleteErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(filesDeleteSchemaSchema, requestOptions);
  }

  /**
   * Gets information about a file.
   *
   * @param token        Authentication token. Requires scope: `files:read`
   * @param file         Specify a file by providing its ID.
   * @param count
   * @param page
   * @param limit        The maximum number of items to return. Fewer than the requested number of items may
   *                               be returned, even if the end of the list hasn't been reached.
   * @param cursor       Parameter for pagination. File comments are paginated for a single file. Set
   *                               `cursor` equal to the `next_cursor` attribute returned by the previous request's
   *                               `response_metadata`. This parameter is optional, but pagination is mandatory: the
   *                               default value simply fetches the first "page" of the collection of comments. See
   *                               [pagination](/docs/pagination) for more details.
   * @return Response from the API call
   */
  async filesInfo(
    token?: string,
    file?: string,
    count?: string,
    page?: string,
    limit?: number,
    cursor?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FilesInfoSchema>> {
    const req = this.createRequest('GET', '/files.info');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      file: [file, optional(string())],
      count: [count, optional(string())],
      page: [page, optional(string())],
      limit: [limit, optional(number())],
      cursor: [cursor, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('file', mapped.file);
    req.query('count', mapped.count);
    req.query('page', mapped.page);
    req.query('limit', mapped.limit);
    req.query('cursor', mapped.cursor);
    req.defaultToError(FilesInfoErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(filesInfoSchemaSchema, requestOptions);
  }

  /**
   * List for a team, in a channel, or from a user with applied filters.
   *
   * @param token                      Authentication token. Requires scope: `files:read`
   * @param user                       Filter files created by a single user.
   * @param channel                    Filter files appearing in a specific channel, indicated by its ID.
   * @param tsFrom                     Filter files created after this timestamp (inclusive).
   * @param tsTo                       Filter files created before this timestamp (inclusive).
   * @param types                      Filter files by type ([see below](#file_types)). You can pass
   *                                              multiple values in the types argument, like `types=spaces,snippets`.
   *                                              The default value is `all`, which does not filter the list.
   * @param count
   * @param page
   * @param showFilesHiddenByLimit     Show truncated file info for files hidden due to being too old, and
   *                                              the team who owns the file being over the file limit.
   * @return Response from the API call
   */
  async filesList(
    token?: string,
    user?: string,
    channel?: string,
    tsFrom?: number,
    tsTo?: number,
    types?: string,
    count?: string,
    page?: string,
    showFilesHiddenByLimit?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FilesListSchema>> {
    const req = this.createRequest('GET', '/files.list');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      user: [user, optional(string())],
      channel: [channel, optional(string())],
      tsFrom: [tsFrom, optional(number())],
      tsTo: [tsTo, optional(number())],
      types: [types, optional(string())],
      count: [count, optional(string())],
      page: [page, optional(string())],
      showFilesHiddenByLimit: [showFilesHiddenByLimit, optional(boolean())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('user', mapped.user);
    req.query('channel', mapped.channel);
    req.query('ts_from', mapped.tsFrom);
    req.query('ts_to', mapped.tsTo);
    req.query('types', mapped.types);
    req.query('count', mapped.count);
    req.query('page', mapped.page);
    req.query('show_files_hidden_by_limit', mapped.showFilesHiddenByLimit);
    req.defaultToError(FilesListErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(filesListSchemaSchema, requestOptions);
  }

  /**
   * Revokes public/external sharing access for a file
   *
   * @param token        Authentication token. Requires scope: `files:write:user`
   * @param file         File to revoke
   * @return Response from the API call
   */
  async filesRevokePublicUrl(
    token?: string,
    file?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FilesRevokePublicUrlSchema>> {
    const req = this.createRequest('POST', '/files.revokePublicURL');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      file: [file, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.header('token', mapped.token);
    req.form({ file: mapped.file });
    req.defaultToError(
      FilesRevokePublicUrlErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(filesRevokePublicUrlSchemaSchema, requestOptions);
  }

  /**
   * Enables a file for public/external sharing.
   *
   * @param token        Authentication token. Requires scope: `files:write:user`
   * @param file         File to share
   * @return Response from the API call
   */
  async filesSharedPublicUrl(
    token?: string,
    file?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FilesSharedPublicUrlSchema>> {
    const req = this.createRequest('POST', '/files.sharedPublicURL');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      file: [file, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.header('token', mapped.token);
    req.form({ file: mapped.file });
    req.defaultToError(
      FilesSharedPublicUrlErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(filesSharedPublicUrlSchemaSchema, requestOptions);
  }

  /**
   * Uploads or creates a file.
   *
   * @param token           Authentication token. Requires scope: `files:write:user`
   * @param file            File contents via `multipart/form-data`. If omitting this parameter, you must
   *                                  submit `content`.
   * @param content         File contents via a POST variable. If omitting this parameter, you must provide
   *                                  a `file`.
   * @param filetype        A [file type](/types/file#file_types) identifier.
   * @param filename        Filename of file.
   * @param title           Title of file.
   * @param initialComment  The message text introducing the file in specified `channels`.
   * @param channels        Comma-separated list of channel names or IDs where the file will be shared.
   * @param threadTs        Provide another message's `ts` value to upload this file as a reply. Never use a
   *                                  reply's `ts` value; use its parent instead.
   * @return Response from the API call
   */
  async filesUpload(
    token?: string,
    file?: string,
    content?: string,
    filetype?: string,
    filename?: string,
    title?: string,
    initialComment?: string,
    channels?: string,
    threadTs?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FilesUploadSchema>> {
    const req = this.createRequest('POST', '/files.upload');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      file: [file, optional(string())],
      content: [content, optional(string())],
      filetype: [filetype, optional(string())],
      filename: [filename, optional(string())],
      title: [title, optional(string())],
      initialComment: [initialComment, optional(string())],
      channels: [channels, optional(string())],
      threadTs: [threadTs, optional(number())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      token: mapped.token,
      file: mapped.file,
      content: mapped.content,
      filetype: mapped.filetype,
      filename: mapped.filename,
      title: mapped.title,
      initial_comment: mapped.initialComment,
      channels: mapped.channels,
      thread_ts: mapped.threadTs,
    });
    req.defaultToError(FilesUploadErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(filesUploadSchemaSchema, requestOptions);
  }
}
