/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  MigrationExchangeSuccessSchema,
  migrationExchangeSuccessSchemaSchema,
} from '../models/migrationExchangeSuccessSchema.js';
import { boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { MigrationExchangeErrorSchemaError } from '../errors/migrationExchangeErrorSchemaError.js';

export class MigrationApi extends BaseApi {
  /**
   * For Enterprise Grid workspaces, map local user IDs to global user IDs
   *
   * @param token        Authentication token. Requires scope: `tokens.basic`
   * @param users        A comma-separated list of user ids, up to 400 per request
   * @param teamId       Specify team_id starts with `T` in case of Org Token
   * @param toOld        Specify `true` to convert `W` global user IDs to workspace-specific `U` IDs.
   *                                Defaults to `false`.
   * @return Response from the API call
   */
  async migrationExchange(
    token: string,
    users: string,
    teamId?: string,
    toOld?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<MigrationExchangeSuccessSchema>> {
    const req = this.createRequest('GET', '/migration.exchange');
    const mapped = req.prepareArgs({
      token: [token, string()],
      users: [users, string()],
      teamId: [teamId, optional(string())],
      toOld: [toOld, optional(boolean())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('users', mapped.users);
    req.query('team_id', mapped.teamId);
    req.query('to_old', mapped.toOld);
    req.defaultToError(
      MigrationExchangeErrorSchemaError,
      'Typical error response when there are no mappings to provide'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(migrationExchangeSuccessSchemaSchema, requestOptions);
  }
}
