/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class OauthV2Api extends BaseApi {
  /**
   * Exchanges a temporary OAuth verifier code for an access token.
   *
   * @param code          The `code` param returned via the OAuth callback.
   * @param clientId      Issued when you created your application.
   * @param clientSecret  Issued when you created your application.
   * @param redirectUri   This must match the originally submitted URI (if one was sent).
   * @return Response from the API call
   */
  async oauthV2Access(
    code: string,
    clientId?: string,
    clientSecret?: string,
    redirectUri?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/oauth.v2.access');
    const mapped = req.prepareArgs({
      code: [code, string()],
      clientId: [clientId, optional(string())],
      clientSecret: [clientSecret, optional(string())],
      redirectUri: [redirectUri, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('code', mapped.code);
    req.query('client_id', mapped.clientId);
    req.query('client_secret', mapped.clientSecret);
    req.query('redirect_uri', mapped.redirectUri);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
