/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class OauthApi extends BaseApi {
  /**
   * Exchanges a temporary OAuth verifier code for an access token.
   *
   * @param clientId       Issued when you created your application.
   * @param clientSecret   Issued when you created your application.
   * @param code           The `code` param returned via the OAuth callback.
   * @param redirectUri    This must match the originally submitted URI (if one was sent).
   * @param singleChannel  Request the user to add your app only to a single channel. Only valid with a
   *                                  [legacy workspace app](https://api.slack.com/legacy-workspace-apps).
   * @return Response from the API call
   */
  async oauthAccess(
    clientId?: string,
    clientSecret?: string,
    code?: string,
    redirectUri?: string,
    singleChannel?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/oauth.access');
    const mapped = req.prepareArgs({
      clientId: [clientId, optional(string())],
      clientSecret: [clientSecret, optional(string())],
      code: [code, optional(string())],
      redirectUri: [redirectUri, optional(string())],
      singleChannel: [singleChannel, optional(boolean())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('client_id', mapped.clientId);
    req.query('client_secret', mapped.clientSecret);
    req.query('code', mapped.code);
    req.query('redirect_uri', mapped.redirectUri);
    req.query('single_channel', mapped.singleChannel);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Exchanges a temporary OAuth verifier code for a workspace token.
   *
   * @param clientId       Issued when you created your application.
   * @param clientSecret   Issued when you created your application.
   * @param code           The `code` param returned via the OAuth callback.
   * @param redirectUri    This must match the originally submitted URI (if one was sent).
   * @param singleChannel  Request the user to add your app only to a single channel.
   * @return Response from the API call
   */
  async oauthToken(
    clientId?: string,
    clientSecret?: string,
    code?: string,
    redirectUri?: string,
    singleChannel?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/oauth.token');
    const mapped = req.prepareArgs({
      clientId: [clientId, optional(string())],
      clientSecret: [clientSecret, optional(string())],
      code: [code, optional(string())],
      redirectUri: [redirectUri, optional(string())],
      singleChannel: [singleChannel, optional(boolean())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('client_id', mapped.clientId);
    req.query('client_secret', mapped.clientSecret);
    req.query('code', mapped.code);
    req.query('redirect_uri', mapped.redirectUri);
    req.query('single_channel', mapped.singleChannel);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
