/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { PinsAddSchema, pinsAddSchemaSchema } from '../models/pinsAddSchema.js';
import {
  PinsRemoveSchema,
  pinsRemoveSchemaSchema,
} from '../models/pinsRemoveSchema.js';
import { optional, string, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { PinsAddErrorSchemaError } from '../errors/pinsAddErrorSchemaError.js';
import { PinsListErrorSchemaError } from '../errors/pinsListErrorSchemaError.js';
import { PinsRemoveErrorSchemaError } from '../errors/pinsRemoveErrorSchemaError.js';

export class PinsApi extends BaseApi {
  /**
   * Pins an item to a channel.
   *
   * @param token        Authentication token. Requires scope: `pins:write`
   * @param channel      Channel to pin the item in.
   * @param timestamp    Timestamp of the message to pin.
   * @return Response from the API call
   */
  async pinsAdd(
    token: string,
    channel: string,
    timestamp?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PinsAddSchema>> {
    const req = this.createRequest('POST', '/pins.add');
    const mapped = req.prepareArgs({
      token: [token, string()],
      channel: [channel, string()],
      timestamp: [timestamp, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ channel: mapped.channel, timestamp: mapped.timestamp });
    req.defaultToError(PinsAddErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(pinsAddSchemaSchema, requestOptions);
  }

  /**
   * Lists items pinned to a channel.
   *
   * @param token        Authentication token. Requires scope: `pins:read`
   * @param channel      Channel to get pinned items for.
   * @return Response from the API call
   */
  async pinsList(
    token: string,
    channel: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/pins.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      channel: [channel, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('channel', mapped.channel);
    req.defaultToError(PinsListErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * Un-pins an item from a channel.
   *
   * @param token        Authentication token. Requires scope: `pins:write`
   * @param channel      Channel where the item is pinned to.
   * @param timestamp    Timestamp of the message to un-pin.
   * @return Response from the API call
   */
  async pinsRemove(
    token: string,
    channel: string,
    timestamp?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PinsRemoveSchema>> {
    const req = this.createRequest('POST', '/pins.remove');
    const mapped = req.prepareArgs({
      token: [token, string()],
      channel: [channel, string()],
      timestamp: [timestamp, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ channel: mapped.channel, timestamp: mapped.timestamp });
    req.defaultToError(PinsRemoveErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(pinsRemoveSchemaSchema, requestOptions);
  }
}
