/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ReactionsAddSchema,
  reactionsAddSchemaSchema,
} from '../models/reactionsAddSchema.js';
import {
  ReactionsListSchema,
  reactionsListSchemaSchema,
} from '../models/reactionsListSchema.js';
import {
  ReactionsRemoveSchema,
  reactionsRemoveSchemaSchema,
} from '../models/reactionsRemoveSchema.js';
import { boolean, number, optional, string, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ReactionsAddErrorSchemaError } from '../errors/reactionsAddErrorSchemaError.js';
import { ReactionsGetErrorSchemaError } from '../errors/reactionsGetErrorSchemaError.js';
import { ReactionsListErrorSchemaError } from '../errors/reactionsListErrorSchemaError.js';
import { ReactionsRemoveErrorSchemaError } from '../errors/reactionsRemoveErrorSchemaError.js';

export class ReactionsApi extends BaseApi {
  /**
   * Adds a reaction to an item.
   *
   * @param channel      Channel where the message to add reaction to was posted.
   * @param name         Reaction (emoji) name.
   * @param timestamp    Timestamp of the message to add reaction to.
   * @param token        Authentication token. Requires scope: `reactions:write`
   * @return Response from the API call
   */
  async reactionsAdd(
    channel: string,
    name: string,
    timestamp: string,
    token: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ReactionsAddSchema>> {
    const req = this.createRequest('POST', '/reactions.add');
    const mapped = req.prepareArgs({
      channel: [channel, string()],
      name: [name, string()],
      timestamp: [timestamp, string()],
      token: [token, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      channel: mapped.channel,
      name: mapped.name,
      timestamp: mapped.timestamp,
    });
    req.defaultToError(ReactionsAddErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(reactionsAddSchemaSchema, requestOptions);
  }

  /**
   * Gets reactions for an item.
   *
   * @param token        Authentication token. Requires scope: `reactions:read`
   * @param channel      Channel where the message to get reactions for was posted.
   * @param file         File to get reactions for.
   * @param fileComment  File comment to get reactions for.
   * @param full         If true always return the complete reaction list.
   * @param timestamp    Timestamp of the message to get reactions for.
   * @return Response from the API call
   */
  async reactionsGet(
    token: string,
    channel?: string,
    file?: string,
    fileComment?: string,
    full?: boolean,
    timestamp?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest('GET', '/reactions.get');
    const mapped = req.prepareArgs({
      token: [token, string()],
      channel: [channel, optional(string())],
      file: [file, optional(string())],
      fileComment: [fileComment, optional(string())],
      full: [full, optional(boolean())],
      timestamp: [timestamp, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('channel', mapped.channel);
    req.query('file', mapped.file);
    req.query('file_comment', mapped.fileComment);
    req.query('full', mapped.full);
    req.query('timestamp', mapped.timestamp);
    req.defaultToError(ReactionsGetErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }

  /**
   * Lists reactions made by a user.
   *
   * @param token        Authentication token. Requires scope: `reactions:read`
   * @param user         Show reactions made by this user. Defaults to the authed user.
   * @param full         If true always return the complete reaction list.
   * @param count
   * @param page
   * @param cursor       Parameter for pagination. Set `cursor` equal to the `next_cursor` attribute
   *                                returned by the previous request's `response_metadata`. This parameter is optional,
   *                                but pagination is mandatory: the default value simply fetches the first "page" of
   *                                the collection.
   * @param limit        The maximum number of items to return. Fewer than the requested number of items
   *                                may be returned, even if the end of the list hasn't been reached.
   * @return Response from the API call
   */
  async reactionsList(
    token: string,
    user?: string,
    full?: boolean,
    count?: number,
    page?: number,
    cursor?: string,
    limit?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ReactionsListSchema>> {
    const req = this.createRequest('GET', '/reactions.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      user: [user, optional(string())],
      full: [full, optional(boolean())],
      count: [count, optional(number())],
      page: [page, optional(number())],
      cursor: [cursor, optional(string())],
      limit: [limit, optional(number())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('user', mapped.user);
    req.query('full', mapped.full);
    req.query('count', mapped.count);
    req.query('page', mapped.page);
    req.query('cursor', mapped.cursor);
    req.query('limit', mapped.limit);
    req.defaultToError(ReactionsListErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(reactionsListSchemaSchema, requestOptions);
  }

  /**
   * Removes a reaction from an item.
   *
   * @param token        Authentication token. Requires scope: `reactions:write`
   * @param name         Reaction (emoji) name.
   * @param file         File to remove reaction from.
   * @param fileComment  File comment to remove reaction from.
   * @param channel      Channel where the message to remove reaction from was posted.
   * @param timestamp    Timestamp of the message to remove reaction from.
   * @return Response from the API call
   */
  async reactionsRemove(
    token: string,
    name: string,
    file?: string,
    fileComment?: string,
    channel?: string,
    timestamp?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ReactionsRemoveSchema>> {
    const req = this.createRequest('POST', '/reactions.remove');
    const mapped = req.prepareArgs({
      token: [token, string()],
      name: [name, string()],
      file: [file, optional(string())],
      fileComment: [fileComment, optional(string())],
      channel: [channel, optional(string())],
      timestamp: [timestamp, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      name: mapped.name,
      file: mapped.file,
      file_comment: mapped.fileComment,
      channel: mapped.channel,
      timestamp: mapped.timestamp,
    });
    req.defaultToError(
      ReactionsRemoveErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(reactionsRemoveSchemaSchema, requestOptions);
  }
}
