/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  RemindersAddSchema,
  remindersAddSchemaSchema,
} from '../models/remindersAddSchema.js';
import {
  RemindersCompleteSchema,
  remindersCompleteSchemaSchema,
} from '../models/remindersCompleteSchema.js';
import {
  RemindersDeleteSchema,
  remindersDeleteSchemaSchema,
} from '../models/remindersDeleteSchema.js';
import {
  RemindersInfoSchema,
  remindersInfoSchemaSchema,
} from '../models/remindersInfoSchema.js';
import {
  RemindersListSchema,
  remindersListSchemaSchema,
} from '../models/remindersListSchema.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { RemindersAddErrorSchemaError } from '../errors/remindersAddErrorSchemaError.js';
import { RemindersCompleteErrorSchemaError } from '../errors/remindersCompleteErrorSchemaError.js';
import { RemindersDeleteErrorSchemaError } from '../errors/remindersDeleteErrorSchemaError.js';
import { RemindersInfoErrorSchemaError } from '../errors/remindersInfoErrorSchemaError.js';
import { RemindersListErrorSchemaError } from '../errors/remindersListErrorSchemaError.js';

export class RemindersApi extends BaseApi {
  /**
   * Creates a reminder.
   *
   * @param token        Authentication token. Requires scope: `reminders:write`
   * @param text         The content of the reminder
   * @param time         When this reminder should happen: the Unix timestamp (up to five years from now),
   *                               the number of seconds until the reminder (if within 24 hours), or a natural language
   *                               description (Ex. "in 15 minutes," or "every Thursday")
   * @param user         The user who will receive the reminder. If no user is specified, the reminder will
   *                               go to user who created it.
   * @return Response from the API call
   */
  async remindersAdd(
    token: string,
    text: string,
    time: string,
    user?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RemindersAddSchema>> {
    const req = this.createRequest('POST', '/reminders.add');
    const mapped = req.prepareArgs({
      token: [token, string()],
      text: [text, string()],
      time: [time, string()],
      user: [user, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ text: mapped.text, time: mapped.time, user: mapped.user });
    req.defaultToError(RemindersAddErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(remindersAddSchemaSchema, requestOptions);
  }

  /**
   * Marks a reminder as complete.
   *
   * @param token        Authentication token. Requires scope: `reminders:write`
   * @param reminder     The ID of the reminder to be marked as complete
   * @return Response from the API call
   */
  async remindersComplete(
    token?: string,
    reminder?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RemindersCompleteSchema>> {
    const req = this.createRequest('POST', '/reminders.complete');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      reminder: [reminder, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.header('token', mapped.token);
    req.form({ reminder: mapped.reminder });
    req.defaultToError(
      RemindersCompleteErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(remindersCompleteSchemaSchema, requestOptions);
  }

  /**
   * Deletes a reminder.
   *
   * @param token        Authentication token. Requires scope: `reminders:write`
   * @param reminder     The ID of the reminder
   * @return Response from the API call
   */
  async remindersDelete(
    token?: string,
    reminder?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RemindersDeleteSchema>> {
    const req = this.createRequest('POST', '/reminders.delete');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      reminder: [reminder, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.header('token', mapped.token);
    req.form({ reminder: mapped.reminder });
    req.defaultToError(
      RemindersDeleteErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(remindersDeleteSchemaSchema, requestOptions);
  }

  /**
   * Gets information about a reminder.
   *
   * @param token        Authentication token. Requires scope: `reminders:read`
   * @param reminder     The ID of the reminder
   * @return Response from the API call
   */
  async remindersInfo(
    token?: string,
    reminder?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RemindersInfoSchema>> {
    const req = this.createRequest('GET', '/reminders.info');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      reminder: [reminder, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('reminder', mapped.reminder);
    req.defaultToError(RemindersInfoErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(remindersInfoSchemaSchema, requestOptions);
  }

  /**
   * Lists all reminders created by or for a given user.
   *
   * @param token        Authentication token. Requires scope: `reminders:read`
   * @return Response from the API call
   */
  async remindersList(
    token?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RemindersListSchema>> {
    const req = this.createRequest('GET', '/reminders.list');
    const mapped = req.prepareArgs({ token: [token, optional(string())] });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.defaultToError(RemindersListErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(remindersListSchemaSchema, requestOptions);
  }
}
