/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { boolean, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class SearchApi extends BaseApi {
  /**
   * Searches for messages matching a query.
   *
   * @param token        Authentication token. Requires scope: `search:read`
   * @param query        Search query.
   * @param count        Pass the number of results you want per "page". Maximum of `100`.
   * @param highlight    Pass a value of `true` to enable query highlight markers (see below).
   * @param page
   * @param sort         Return matches sorted by either `score` or `timestamp`.
   * @param sortDir      Change sort direction to ascending (`asc`) or descending (`desc`).
   * @return Response from the API call
   */
  async searchMessages(
    token: string,
    query: string,
    count?: number,
    highlight?: boolean,
    page?: number,
    sort?: string,
    sortDir?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/search.messages');
    const mapped = req.prepareArgs({
      token: [token, string()],
      query: [query, string()],
      count: [count, optional(number())],
      highlight: [highlight, optional(boolean())],
      page: [page, optional(number())],
      sort: [sort, optional(string())],
      sortDir: [sortDir, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('query', mapped.query);
    req.query('count', mapped.count);
    req.query('highlight', mapped.highlight);
    req.query('page', mapped.page);
    req.query('sort', mapped.sort);
    req.query('sort_dir', mapped.sortDir);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
