/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import {
  TeamAccessLogsSchema,
  teamAccessLogsSchemaSchema,
} from '../models/teamAccessLogsSchema.js';
import {
  TeamInfoSchema,
  teamInfoSchemaSchema,
} from '../models/teamInfoSchema.js';
import {
  TeamIntegrationLogsSchema,
  teamIntegrationLogsSchemaSchema,
} from '../models/teamIntegrationLogsSchema.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';
import { TeamAccessLogsErrorSchemaError } from '../errors/teamAccessLogsErrorSchemaError.js';
import { TeamInfoErrorSchemaError } from '../errors/teamInfoErrorSchemaError.js';
import { TeamIntegrationLogsErrorSchemaError } from '../errors/teamIntegrationLogsErrorSchemaError.js';

export class TeamApi extends BaseApi {
  /**
   * Gets the access logs for the current team.
   *
   * @param token        Authentication token. Requires scope: `admin`
   * @param before       End of time range of logs to include in results (inclusive).
   * @param count
   * @param page
   * @return Response from the API call
   */
  async teamAccessLogs(
    token: string,
    before?: string,
    count?: string,
    page?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TeamAccessLogsSchema>> {
    const req = this.createRequest('GET', '/team.accessLogs');
    const mapped = req.prepareArgs({
      token: [token, string()],
      before: [before, optional(string())],
      count: [count, optional(string())],
      page: [page, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('before', mapped.before);
    req.query('count', mapped.count);
    req.query('page', mapped.page);
    req.defaultToError(
      TeamAccessLogsErrorSchemaError,
      'A workspace must be on a paid plan to use this method, otherwise the `paid_only` error is thrown:'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(teamAccessLogsSchemaSchema, requestOptions);
  }

  /**
   * Gets billable users information for the current team.
   *
   * @param token        Authentication token. Requires scope: `admin`
   * @param user         A user to retrieve the billable information for. Defaults to all users.
   * @return Response from the API call
   */
  async teamBillableInfo(
    token: string,
    user?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/team.billableInfo');
    const mapped = req.prepareArgs({
      token: [token, string()],
      user: [user, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('user', mapped.user);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Gets information about the current team.
   *
   * @param token        Authentication token. Requires scope: `team:read`
   * @param team         Team to get info on, if omitted, will return information about the current team.
   *                               Will only return team that the authenticated token is allowed to see through
   *                               external shared channels
   * @return Response from the API call
   */
  async teamInfo(
    token: string,
    team?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TeamInfoSchema>> {
    const req = this.createRequest('GET', '/team.info');
    const mapped = req.prepareArgs({
      token: [token, string()],
      team: [team, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('team', mapped.team);
    req.defaultToError(TeamInfoErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(teamInfoSchemaSchema, requestOptions);
  }

  /**
   * Gets the integration logs for the current team.
   *
   * @param token        Authentication token. Requires scope: `admin`
   * @param appId        Filter logs to this Slack app. Defaults to all logs.
   * @param changeType   Filter logs with this change type. Defaults to all logs.
   * @param count
   * @param page
   * @param serviceId    Filter logs to this service. Defaults to all logs.
   * @param user         Filter logs generated by this user’s actions. Defaults to all logs.
   * @return Response from the API call
   */
  async teamIntegrationLogs(
    token: string,
    appId?: string,
    changeType?: string,
    count?: string,
    page?: string,
    serviceId?: string,
    user?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TeamIntegrationLogsSchema>> {
    const req = this.createRequest('GET', '/team.integrationLogs');
    const mapped = req.prepareArgs({
      token: [token, string()],
      appId: [appId, optional(string())],
      changeType: [changeType, optional(string())],
      count: [count, optional(string())],
      page: [page, optional(string())],
      serviceId: [serviceId, optional(string())],
      user: [user, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('app_id', mapped.appId);
    req.query('change_type', mapped.changeType);
    req.query('count', mapped.count);
    req.query('page', mapped.page);
    req.query('service_id', mapped.serviceId);
    req.query('user', mapped.user);
    req.defaultToError(
      TeamIntegrationLogsErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(teamIntegrationLogsSchemaSchema, requestOptions);
  }
}
