/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  UsergroupsUsersListSchema,
  usergroupsUsersListSchemaSchema,
} from '../models/usergroupsUsersListSchema.js';
import {
  UsergroupsUsersUpdateSchema,
  usergroupsUsersUpdateSchemaSchema,
} from '../models/usergroupsUsersUpdateSchema.js';
import { boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { UsergroupsUsersListErrorSchemaError } from '../errors/usergroupsUsersListErrorSchemaError.js';
import { UsergroupsUsersUpdateErrorSchemaError } from '../errors/usergroupsUsersUpdateErrorSchemaError.js';

export class UsergroupsUsersApi extends BaseApi {
  /**
   * List all users in a User Group
   *
   * @param token            Authentication token. Requires scope: `usergroups:read`
   * @param usergroup        The encoded ID of the User Group to update.
   * @param includeDisabled  Allow results that involve disabled User Groups.
   * @return Response from the API call
   */
  async usergroupsUsersList(
    token: string,
    usergroup: string,
    includeDisabled?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsergroupsUsersListSchema>> {
    const req = this.createRequest('GET', '/usergroups.users.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      usergroup: [usergroup, string()],
      includeDisabled: [includeDisabled, optional(boolean())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('usergroup', mapped.usergroup);
    req.query('include_disabled', mapped.includeDisabled);
    req.defaultToError(
      UsergroupsUsersListErrorSchemaError,
      'Standard failure response when used with an invalid token'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usergroupsUsersListSchemaSchema, requestOptions);
  }

  /**
   * Update the list of users for a User Group
   *
   * @param token         Authentication token. Requires scope: `usergroups:write`
   * @param usergroup     The encoded ID of the User Group to update.
   * @param users         A comma separated string of encoded user IDs that represent the entire list of
   *                                 users for the User Group.
   * @param includeCount  Include the number of users in the User Group.
   * @return Response from the API call
   */
  async usergroupsUsersUpdate(
    token: string,
    usergroup: string,
    users: string,
    includeCount?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsergroupsUsersUpdateSchema>> {
    const req = this.createRequest('POST', '/usergroups.users.update');
    const mapped = req.prepareArgs({
      token: [token, string()],
      usergroup: [usergroup, string()],
      users: [users, string()],
      includeCount: [includeCount, optional(boolean())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      usergroup: mapped.usergroup,
      users: mapped.users,
      include_count: mapped.includeCount,
    });
    req.defaultToError(
      UsergroupsUsersUpdateErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usergroupsUsersUpdateSchemaSchema, requestOptions);
  }
}
