/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ApiMethodUsersGetPresence,
  apiMethodUsersGetPresenceSchema,
} from '../models/apiMethodUsersGetPresence.js';
import {
  UsersConversationsSuccessSchema,
  usersConversationsSuccessSchemaSchema,
} from '../models/usersConversationsSuccessSchema.js';
import {
  UsersDeletePhotoSchema,
  usersDeletePhotoSchemaSchema,
} from '../models/usersDeletePhotoSchema.js';
import {
  UsersInfoSuccessSchema,
  usersInfoSuccessSchemaSchema,
} from '../models/usersInfoSuccessSchema.js';
import {
  UsersListSchema,
  usersListSchemaSchema,
} from '../models/usersListSchema.js';
import {
  UsersLookupByEmailSuccessSchema,
  usersLookupByEmailSuccessSchemaSchema,
} from '../models/usersLookupByEmailSuccessSchema.js';
import {
  UsersSetActiveSchema,
  usersSetActiveSchemaSchema,
} from '../models/usersSetActiveSchema.js';
import {
  UsersSetPhotoSchema,
  usersSetPhotoSchemaSchema,
} from '../models/usersSetPhotoSchema.js';
import {
  UsersSetPresenceSchema,
  usersSetPresenceSchemaSchema,
} from '../models/usersSetPresenceSchema.js';
import { boolean, number, optional, string, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { UsersConversationsErrorSchemaError } from '../errors/usersConversationsErrorSchemaError.js';
import { UsersCountsErrorSchemaError } from '../errors/usersCountsErrorSchemaError.js';
import { UsersDeletePhotoErrorSchemaError } from '../errors/usersDeletePhotoErrorSchemaError.js';
import { UsersIdentityErrorSchemaError } from '../errors/usersIdentityErrorSchemaError.js';
import { UsersInfoErrorSchemaError } from '../errors/usersInfoErrorSchemaError.js';
import { UsersListErrorSchemaError } from '../errors/usersListErrorSchemaError.js';
import { UsersLookupByEmailErrorSchemaError } from '../errors/usersLookupByEmailErrorSchemaError.js';
import { UsersSetActiveErrorSchemaError } from '../errors/usersSetActiveErrorSchemaError.js';
import { UsersSetPhotoErrorSchemaError } from '../errors/usersSetPhotoErrorSchemaError.js';
import { UsersSetPresenceErrorSchemaError } from '../errors/usersSetPresenceErrorSchemaError.js';

export class UsersApi extends BaseApi {
  /**
   * List conversations the calling user may access.
   *
   * @param token            Authentication token. Requires scope: `conversations:read`
   * @param user             Browse conversations by a specific user ID's membership. Non-public channels
   *                                    are restricted to those where the calling user shares membership.
   * @param types            Mix and match channel types by providing a comma-separated list of any
   *                                    combination of `public_channel`, `private_channel`, `mpim`, `im`
   * @param excludeArchived  Set to `true` to exclude archived channels from the list
   * @param limit            The maximum number of items to return. Fewer than the requested number of
   *                                    items may be returned, even if the end of the list hasn't been reached. Must be
   *                                    an integer no larger than 1000.
   * @param cursor           Paginate through collections of data by setting the `cursor` parameter to a
   *                                    `next_cursor` attribute returned by a previous request's `response_metadata`.
   *                                    Default value fetches the first "page" of the collection.
   * @return Response from the API call
   */
  async usersConversations(
    token?: string,
    user?: string,
    types?: string,
    excludeArchived?: boolean,
    limit?: number,
    cursor?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsersConversationsSuccessSchema>> {
    const req = this.createRequest('GET', '/users.conversations');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      user: [user, optional(string())],
      types: [types, optional(string())],
      excludeArchived: [excludeArchived, optional(boolean())],
      limit: [limit, optional(number())],
      cursor: [cursor, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('user', mapped.user);
    req.query('types', mapped.types);
    req.query('exclude_archived', mapped.excludeArchived);
    req.query('limit', mapped.limit);
    req.query('cursor', mapped.cursor);
    req.defaultToError(
      UsersConversationsErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(
      usersConversationsSuccessSchemaSchema,
      requestOptions
    );
  }

  /**
   * Delete the user profile photo
   *
   * @param token        Authentication token. Requires scope: `users.profile:write`
   * @return Response from the API call
   */
  async usersDeletePhoto(
    token: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsersDeletePhotoSchema>> {
    const req = this.createRequest('POST', '/users.deletePhoto');
    const mapped = req.prepareArgs({ token: [token, string()] });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ token: mapped.token });
    req.defaultToError(
      UsersDeletePhotoErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usersDeletePhotoSchemaSchema, requestOptions);
  }

  /**
   * Gets user presence information.
   *
   * @param token        Authentication token. Requires scope: `users:read`
   * @param user         User to get presence info on. Defaults to the authed user.
   * @return Response from the API call
   */
  async usersGetPresence(
    token: string,
    user?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ApiMethodUsersGetPresence>> {
    const req = this.createRequest('GET', '/users.getPresence');
    const mapped = req.prepareArgs({
      token: [token, string()],
      user: [user, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('user', mapped.user);
    req.defaultToError(UsersCountsErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(apiMethodUsersGetPresenceSchema, requestOptions);
  }

  /**
   * Get a user's identity.
   *
   * @param token        Authentication token. Requires scope: `identity.basic`
   * @return Response from the API call
   */
  async usersIdentity(
    token?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('GET', '/users.identity');
    const mapped = req.prepareArgs({ token: [token, optional(string())] });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.defaultToError(UsersIdentityErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * Gets information about a user.
   *
   * @param token          Authentication token. Requires scope: `users:read`
   * @param includeLocale  Set this to `true` to receive the locale for this user. Defaults to `false`
   * @param user           User to get info on
   * @return Response from the API call
   */
  async usersInfo(
    token: string,
    includeLocale?: boolean,
    user?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsersInfoSuccessSchema>> {
    const req = this.createRequest('GET', '/users.info');
    const mapped = req.prepareArgs({
      token: [token, string()],
      includeLocale: [includeLocale, optional(boolean())],
      user: [user, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('include_locale', mapped.includeLocale);
    req.query('user', mapped.user);
    req.defaultToError(UsersInfoErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usersInfoSuccessSchemaSchema, requestOptions);
  }

  /**
   * Lists all users in a Slack team.
   *
   * @param token          Authentication token. Requires scope: `users:read`
   * @param limit          The maximum number of items to return. Fewer than the requested number of items
   *                                  may be returned, even if the end of the users list hasn't been reached. Providing
   *                                  no `limit` value will result in Slack attempting to deliver you the entire result
   *                                  set. If the collection is too large you may experience `limit_required` or HTTP
   *                                  500 errors.
   * @param cursor         Paginate through collections of data by setting the `cursor` parameter to a
   *                                  `next_cursor` attribute returned by a previous request's `response_metadata`.
   *                                  Default value fetches the first "page" of the collection.
   * @param includeLocale  Set this to `true` to receive the locale for users. Defaults to `false`
   * @return Response from the API call
   */
  async usersList(
    token?: string,
    limit?: number,
    cursor?: string,
    includeLocale?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsersListSchema>> {
    const req = this.createRequest('GET', '/users.list');
    const mapped = req.prepareArgs({
      token: [token, optional(string())],
      limit: [limit, optional(number())],
      cursor: [cursor, optional(string())],
      includeLocale: [includeLocale, optional(boolean())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('limit', mapped.limit);
    req.query('cursor', mapped.cursor);
    req.query('include_locale', mapped.includeLocale);
    req.defaultToError(UsersListErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usersListSchemaSchema, requestOptions);
  }

  /**
   * Find a user with an email address.
   *
   * @param token        Authentication token. Requires scope: `users:read.email`
   * @param email        An email address belonging to a user in the workspace
   * @return Response from the API call
   */
  async usersLookupByEmail(
    token: string,
    email: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsersLookupByEmailSuccessSchema>> {
    const req = this.createRequest('GET', '/users.lookupByEmail');
    const mapped = req.prepareArgs({
      token: [token, string()],
      email: [email, string()],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('email', mapped.email);
    req.defaultToError(
      UsersLookupByEmailErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(
      usersLookupByEmailSuccessSchemaSchema,
      requestOptions
    );
  }

  /**
   * Marked a user as active. Deprecated and non-functional.
   *
   * @param token        Authentication token. Requires scope: `users:write`
   * @return Response from the API call
   */
  async usersSetActive(
    token: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsersSetActiveSchema>> {
    const req = this.createRequest('POST', '/users.setActive');
    const mapped = req.prepareArgs({ token: [token, string()] });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.defaultToError(
      UsersSetActiveErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usersSetActiveSchemaSchema, requestOptions);
  }

  /**
   * Set the user profile photo
   *
   * @param token        Authentication token. Requires scope: `users.profile:write`
   * @param cropW        Width/height of crop box (always square)
   * @param cropX        X coordinate of top-left corner of crop box
   * @param cropY        Y coordinate of top-left corner of crop box
   * @param image        File contents via `multipart/form-data`.
   * @return Response from the API call
   */
  async usersSetPhoto(
    token: string,
    cropW?: string,
    cropX?: string,
    cropY?: string,
    image?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsersSetPhotoSchema>> {
    const req = this.createRequest('POST', '/users.setPhoto');
    const mapped = req.prepareArgs({
      token: [token, string()],
      cropW: [cropW, optional(string())],
      cropX: [cropX, optional(string())],
      cropY: [cropY, optional(string())],
      image: [image, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      token: mapped.token,
      crop_w: mapped.cropW,
      crop_x: mapped.cropX,
      crop_y: mapped.cropY,
      image: mapped.image,
    });
    req.defaultToError(UsersSetPhotoErrorSchemaError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usersSetPhotoSchemaSchema, requestOptions);
  }

  /**
   * Manually sets user presence.
   *
   * @param token        Authentication token. Requires scope: `users:write`
   * @param presence     Either `auto` or `away`
   * @return Response from the API call
   */
  async usersSetPresence(
    token: string,
    presence: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsersSetPresenceSchema>> {
    const req = this.createRequest('POST', '/users.setPresence');
    const mapped = req.prepareArgs({
      token: [token, string()],
      presence: [presence, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({ presence: mapped.presence });
    req.defaultToError(
      UsersSetPresenceErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usersSetPresenceSchemaSchema, requestOptions);
  }
}
