/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  UsersProfileGetSchema,
  usersProfileGetSchemaSchema,
} from '../models/usersProfileGetSchema.js';
import {
  UsersProfileSetSchema,
  usersProfileSetSchemaSchema,
} from '../models/usersProfileSetSchema.js';
import { boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { UsersProfileGetErrorSchemaError } from '../errors/usersProfileGetErrorSchemaError.js';
import { UsersProfileSetErrorSchemaError } from '../errors/usersProfileSetErrorSchemaError.js';

export class UsersProfileApi extends BaseApi {
  /**
   * Retrieves a user's profile information.
   *
   * @param token          Authentication token. Requires scope: `users.profile:read`
   * @param includeLabels  Include labels for each ID in custom profile fields
   * @param user           User to retrieve profile info for
   * @return Response from the API call
   */
  async usersProfileGet(
    token: string,
    includeLabels?: boolean,
    user?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsersProfileGetSchema>> {
    const req = this.createRequest('GET', '/users.profile.get');
    const mapped = req.prepareArgs({
      token: [token, string()],
      includeLabels: [includeLabels, optional(boolean())],
      user: [user, optional(string())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('include_labels', mapped.includeLabels);
    req.query('user', mapped.user);
    req.defaultToError(
      UsersProfileGetErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usersProfileGetSchemaSchema, requestOptions);
  }

  /**
   * Set the profile information for a user.
   *
   * @param token        Authentication token. Requires scope: `users.profile:write`
   * @param name         Name of a single key to set. Usable only if `profile` is not passed.
   * @param profile      Collection of key:value pairs presented as a URL-encoded JSON hash. At most 50
   *                               fields may be set. Each field name is limited to 255 characters.
   * @param user         ID of user to change. This argument may only be specified by team admins on paid
   *                               teams.
   * @param value        Value to set a single key to. Usable only if `profile` is not passed.
   * @return Response from the API call
   */
  async usersProfileSet(
    token: string,
    name?: string,
    profile?: string,
    user?: string,
    value?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsersProfileSetSchema>> {
    const req = this.createRequest('POST', '/users.profile.set');
    const mapped = req.prepareArgs({
      token: [token, string()],
      name: [name, optional(string())],
      profile: [profile, optional(string())],
      user: [user, optional(string())],
      value: [value, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      name: mapped.name,
      profile: mapped.profile,
      user: mapped.user,
      value: mapped.value,
    });
    req.defaultToError(
      UsersProfileSetErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usersProfileSetSchemaSchema, requestOptions);
  }
}
