/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  UsergroupsCreateSchema,
  usergroupsCreateSchemaSchema,
} from '../models/usergroupsCreateSchema.js';
import {
  UsergroupsDisableSchema,
  usergroupsDisableSchemaSchema,
} from '../models/usergroupsDisableSchema.js';
import {
  UsergroupsEnableSchema,
  usergroupsEnableSchemaSchema,
} from '../models/usergroupsEnableSchema.js';
import {
  UsergroupsListSchema,
  usergroupsListSchemaSchema,
} from '../models/usergroupsListSchema.js';
import {
  UsergroupsUpdateSchema,
  usergroupsUpdateSchemaSchema,
} from '../models/usergroupsUpdateSchema.js';
import { boolean, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { UsergroupsCreateErrorSchemaError } from '../errors/usergroupsCreateErrorSchemaError.js';
import { UsergroupsDisableErrorSchemaError } from '../errors/usergroupsDisableErrorSchemaError.js';
import { UsergroupsEnableErrorSchemaError } from '../errors/usergroupsEnableErrorSchemaError.js';
import { UsergroupsListErrorSchemaError } from '../errors/usergroupsListErrorSchemaError.js';
import { UsergroupsUpdateErrorSchemaError } from '../errors/usergroupsUpdateErrorSchemaError.js';

export class UsergroupsApi extends BaseApi {
  /**
   * Create a User Group
   *
   * @param token         Authentication token. Requires scope: `usergroups:write`
   * @param name          A name for the User Group. Must be unique among User Groups.
   * @param channels      A comma separated string of encoded channel IDs for which the User Group uses as
   *                                 a default.
   * @param description   A short description of the User Group.
   * @param handle        A mention handle. Must be unique among channels, users and User Groups.
   * @param includeCount  Include the number of users in each User Group.
   * @return Response from the API call
   */
  async usergroupsCreate(
    token: string,
    name: string,
    channels?: string,
    description?: string,
    handle?: string,
    includeCount?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsergroupsCreateSchema>> {
    const req = this.createRequest('POST', '/usergroups.create');
    const mapped = req.prepareArgs({
      token: [token, string()],
      name: [name, string()],
      channels: [channels, optional(string())],
      description: [description, optional(string())],
      handle: [handle, optional(string())],
      includeCount: [includeCount, optional(boolean())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      name: mapped.name,
      channels: mapped.channels,
      description: mapped.description,
      handle: mapped.handle,
      include_count: mapped.includeCount,
    });
    req.defaultToError(
      UsergroupsCreateErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usergroupsCreateSchemaSchema, requestOptions);
  }

  /**
   * Disable an existing User Group
   *
   * @param token         Authentication token. Requires scope: `usergroups:write`
   * @param usergroup     The encoded ID of the User Group to disable.
   * @param includeCount  Include the number of users in the User Group.
   * @return Response from the API call
   */
  async usergroupsDisable(
    token: string,
    usergroup: string,
    includeCount?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsergroupsDisableSchema>> {
    const req = this.createRequest('POST', '/usergroups.disable');
    const mapped = req.prepareArgs({
      token: [token, string()],
      usergroup: [usergroup, string()],
      includeCount: [includeCount, optional(boolean())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      usergroup: mapped.usergroup,
      include_count: mapped.includeCount,
    });
    req.defaultToError(
      UsergroupsDisableErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usergroupsDisableSchemaSchema, requestOptions);
  }

  /**
   * Enable a User Group
   *
   * @param token         Authentication token. Requires scope: `usergroups:write`
   * @param usergroup     The encoded ID of the User Group to enable.
   * @param includeCount  Include the number of users in the User Group.
   * @return Response from the API call
   */
  async usergroupsEnable(
    token: string,
    usergroup: string,
    includeCount?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsergroupsEnableSchema>> {
    const req = this.createRequest('POST', '/usergroups.enable');
    const mapped = req.prepareArgs({
      token: [token, string()],
      usergroup: [usergroup, string()],
      includeCount: [includeCount, optional(boolean())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      usergroup: mapped.usergroup,
      include_count: mapped.includeCount,
    });
    req.defaultToError(
      UsergroupsEnableErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usergroupsEnableSchemaSchema, requestOptions);
  }

  /**
   * List all User Groups for a team
   *
   * @param token            Authentication token. Requires scope: `usergroups:read`
   * @param includeUsers     Include the list of users for each User Group.
   * @param includeCount     Include the number of users in each User Group.
   * @param includeDisabled  Include disabled User Groups.
   * @return Response from the API call
   */
  async usergroupsList(
    token: string,
    includeUsers?: boolean,
    includeCount?: boolean,
    includeDisabled?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsergroupsListSchema>> {
    const req = this.createRequest('GET', '/usergroups.list');
    const mapped = req.prepareArgs({
      token: [token, string()],
      includeUsers: [includeUsers, optional(boolean())],
      includeCount: [includeCount, optional(boolean())],
      includeDisabled: [includeDisabled, optional(boolean())],
    });
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('token', mapped.token);
    req.query('include_users', mapped.includeUsers);
    req.query('include_count', mapped.includeCount);
    req.query('include_disabled', mapped.includeDisabled);
    req.defaultToError(
      UsergroupsListErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usergroupsListSchemaSchema, requestOptions);
  }

  /**
   * Update an existing User Group
   *
   * @param token         Authentication token. Requires scope: `usergroups:write`
   * @param usergroup     The encoded ID of the User Group to update.
   * @param handle        A mention handle. Must be unique among channels, users and User Groups.
   * @param description   A short description of the User Group.
   * @param channels      A comma separated string of encoded channel IDs for which the User Group uses as
   *                                 a default.
   * @param includeCount  Include the number of users in the User Group.
   * @param name          A name for the User Group. Must be unique among User Groups.
   * @return Response from the API call
   */
  async usergroupsUpdate(
    token: string,
    usergroup: string,
    handle?: string,
    description?: string,
    channels?: string,
    includeCount?: boolean,
    name?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UsergroupsUpdateSchema>> {
    const req = this.createRequest('POST', '/usergroups.update');
    const mapped = req.prepareArgs({
      token: [token, string()],
      usergroup: [usergroup, string()],
      handle: [handle, optional(string())],
      description: [description, optional(string())],
      channels: [channels, optional(string())],
      includeCount: [includeCount, optional(boolean())],
      name: [name, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.form({
      usergroup: mapped.usergroup,
      handle: mapped.handle,
      description: mapped.description,
      channels: mapped.channels,
      include_count: mapped.includeCount,
      name: mapped.name,
    });
    req.defaultToError(
      UsergroupsUpdateErrorSchemaError,
      'Typical error response'
    );
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(usergroupsUpdateSchemaSchema, requestOptions);
  }
}
