/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  DefaultSuccessTemplate,
  defaultSuccessTemplateSchema,
} from '../models/defaultSuccessTemplate.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { DefaultErrorTemplateError } from '../errors/defaultErrorTemplateError.js';

export class WorkflowsApi extends BaseApi {
  /**
   * Indicate that an app's step in a workflow completed execution.
   *
   * @param token                    Authentication token. Requires scope: `workflow.steps:execute`
   * @param workflowStepExecuteId    Context identifier that maps to the correct workflow step execution.
   * @param outputs                  Key-value object of outputs from your step. Keys of this object reflect
   *                                           the configured `key` properties of your
   *                                           [`outputs`](/reference/workflows/workflow_step#output) array from your
   *                                           `workflow_step` object.
   * @return Response from the API call
   */
  async workflowsStepCompleted(
    token: string,
    workflowStepExecuteId: string,
    outputs?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/workflows.stepCompleted');
    const mapped = req.prepareArgs({
      token: [token, string()],
      workflowStepExecuteId: [workflowStepExecuteId, string()],
      outputs: [outputs, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('workflow_step_execute_id', mapped.workflowStepExecuteId);
    req.query('outputs', mapped.outputs);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Indicate that an app's step in a workflow failed to execute.
   *
   * @param token                    Authentication token. Requires scope: `workflow.steps:execute`
   * @param workflowStepExecuteId    Context identifier that maps to the correct workflow step execution.
   * @param error                    A JSON-based object with a `message` property that should contain a
   *                                           human readable error message.
   * @return Response from the API call
   */
  async workflowsStepFailed(
    token: string,
    workflowStepExecuteId: string,
    error: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/workflows.stepFailed');
    const mapped = req.prepareArgs({
      token: [token, string()],
      workflowStepExecuteId: [workflowStepExecuteId, string()],
      error: [error, string()],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('workflow_step_execute_id', mapped.workflowStepExecuteId);
    req.query('error', mapped.error);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }

  /**
   * Update the configuration for a workflow extension step.
   *
   * @param token                 Authentication token. Requires scope: `workflow.steps:execute`
   * @param workflowStepEditId    A context identifier provided with `view_submission` payloads used to call
   *                                        back to `workflows.updateStep`.
   * @param inputs                A JSON key-value map of inputs required from a user during configuration.
   *                                        This is the data your app expects to receive when the workflow step starts.
   *                                        **Please note**: the embedded variable format is set and replaced by the
   *                                        workflow system. You cannot create custom variables that will be replaced
   *                                        at runtime. [Read more about variables in workflow steps
   *                                        here](/workflows/steps#variables).
   * @param outputs               An JSON array of output objects used during step execution. This is the
   *                                        data your app agrees to provide when your workflow step was executed.
   * @param stepName              An optional field that can be used to override the step name that is shown
   *                                        in the Workflow Builder.
   * @param stepImageUrl          An optional field that can be used to override app image that is shown in
   *                                        the Workflow Builder.
   * @return Response from the API call
   */
  async workflowsUpdateStep(
    token: string,
    workflowStepEditId: string,
    inputs?: string,
    outputs?: string,
    stepName?: string,
    stepImageUrl?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<DefaultSuccessTemplate>> {
    const req = this.createRequest('GET', '/workflows.updateStep');
    const mapped = req.prepareArgs({
      token: [token, string()],
      workflowStepEditId: [workflowStepEditId, string()],
      inputs: [inputs, optional(string())],
      outputs: [outputs, optional(string())],
      stepName: [stepName, optional(string())],
      stepImageUrl: [stepImageUrl, optional(string())],
    });
    req.header('token', mapped.token);
    req.header('Content-Type', 'application/x-www-form-urlencoded');
    req.query('workflow_step_edit_id', mapped.workflowStepEditId);
    req.query('inputs', mapped.inputs);
    req.query('outputs', mapped.outputs);
    req.query('step_name', mapped.stepName);
    req.query('step_image_url', mapped.stepImageUrl);
    req.defaultToError(DefaultErrorTemplateError, 'Typical error response');
    req.authenticate([{ slackAuth: true }]);
    return req.callAsJson(defaultSuccessTemplateSchema, requestOptions);
  }
}
