/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AdminConversationsUnarchiveErrorEnum
 */
export enum AdminConversationsUnarchiveErrorEnum {
  FeatureNotEnabled = 'feature_not_enabled',
  ChannelNotFound = 'channel_not_found',
  ChannelNotArchived = 'channel_not_archived',
  ChannelTypeNotSupported = 'channel_type_not_supported',
  RestrictedAction = 'restricted_action',
  CouldNotUnarchiveChannel = 'could_not_unarchive_channel',
  DefaultOrgWideChannel = 'default_org_wide_channel',
  MissingScope = 'missing_scope',
}

/**
 * Schema for AdminConversationsUnarchiveErrorEnum
 */
export const adminConversationsUnarchiveErrorEnumSchema: Schema<AdminConversationsUnarchiveErrorEnum> = stringEnum(
  AdminConversationsUnarchiveErrorEnum
);
