/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AdminConversationsSetConversationPrefsErrorEnum
 */
export enum AdminConversationsSetConversationPrefsErrorEnum {
  FeatureNotEnabled = 'feature_not_enabled',
  NotAnAdmin = 'not_an_admin',
  ChannelNotFound = 'channel_not_found',
  ChannelTypeNotSupported = 'channel_type_not_supported',
  RestrictedAction = 'restricted_action',
  MissingScope = 'missing_scope',
  CouldNotSetChannelPref = 'could_not_set_channel_pref',
  DefaultOrgWideChannel = 'default_org_wide_channel',
}

/**
 * Schema for AdminConversationsSetConversationPrefsErrorEnum
 */
export const adminConversationsSetConversationPrefsErrorEnumSchema: Schema<AdminConversationsSetConversationPrefsErrorEnum> = stringEnum(
  AdminConversationsSetConversationPrefsErrorEnum
);
