/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AdminConversationsCreateErrorEnum
 */
export enum AdminConversationsCreateErrorEnum {
  FeatureNotEnabled = 'feature_not_enabled',
  NameTaken = 'name_taken',
  RestrictedAction = 'restricted_action',
  TeamNotFound = 'team_not_found',
  InvalidTeam = 'invalid_team',
  InvalidName = 'invalid_name',
  CouldNotCreateChannel = 'could_not_create_channel',
  TeamIdOrOrgRequired = 'team_id_or_org_required',
}

/**
 * Schema for AdminConversationsCreateErrorEnum
 */
export const adminConversationsCreateErrorEnumSchema: Schema<AdminConversationsCreateErrorEnum> = stringEnum(
  AdminConversationsCreateErrorEnum
);
