/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response of admin.conversations.unarchive */
export interface AdminConversationsUnarchiveSchema {
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export const adminConversationsUnarchiveSchemaSchema: Schema<AdminConversationsUnarchiveSchema> = typedExpandoObject(
  { ok: ['ok', string()] },
  'additionalProperties',
  optional(unknown())
);
