/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AdminConversationsDeleteErrorEnum
 */
export enum AdminConversationsDeleteErrorEnum {
  FeatureNotEnabled = 'feature_not_enabled',
  NotAnAdmin = 'not_an_admin',
  ChannelNotFound = 'channel_not_found',
  ChannelTypeNotSupported = 'channel_type_not_supported',
  DefaultOrgWideChannel = 'default_org_wide_channel',
  RestrictedAction = 'restricted_action',
  CouldNotDeleteChannel = 'could_not_delete_channel',
  MissingScope = 'missing_scope',
}

/**
 * Schema for AdminConversationsDeleteErrorEnum
 */
export const adminConversationsDeleteErrorEnumSchema: Schema<AdminConversationsDeleteErrorEnum> = stringEnum(
  AdminConversationsDeleteErrorEnum
);
