/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AdminConversationsConvertToPrivateErrorEnum
 */
export enum AdminConversationsConvertToPrivateErrorEnum {
  FeatureNotEnabled = 'feature_not_enabled',
  RestrictedAction = 'restricted_action',
  NameTaken = 'name_taken',
  ChannelNotFound = 'channel_not_found',
  ChannelTypeNotSupported = 'channel_type_not_supported',
  DefaultOrgWideChannel = 'default_org_wide_channel',
  MethodNotSupportedForChannelType = 'method_not_supported_for_channel_type',
  CouldNotConvertChannel = 'could_not_convert_channel',
  ExternalChannelMigrating = 'external_channel_migrating',
}

/**
 * Schema for AdminConversationsConvertToPrivateErrorEnum
 */
export const adminConversationsConvertToPrivateErrorEnumSchema: Schema<AdminConversationsConvertToPrivateErrorEnum> = stringEnum(
  AdminConversationsConvertToPrivateErrorEnum
);
