/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseMetadata,
  responseMetadataSchema,
} from './responseMetadata.js';

/** Schema for successful response of admin.conversations.getTeams */
export interface AdminConversationsGetTeamsSchema {
  ok: string;
  responseMetadata?: ResponseMetadata;
  teamIds: string[];
  additionalProperties?: Record<string, unknown>;
}

export const adminConversationsGetTeamsSchemaSchema: Schema<AdminConversationsGetTeamsSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        ok: ['ok', string()],
        responseMetadata: [
          'response_metadata',
          optional(responseMetadataSchema),
        ],
        teamIds: ['team_ids', array(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
