/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response of admin.conversations.create */
export interface AdminConversationsCreateSchema {
  channelId?: string;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export const adminConversationsCreateSchemaSchema: Schema<AdminConversationsCreateSchema> = typedExpandoObject(
  { channelId: ['channel_id', optional(string())], ok: ['ok', string()] },
  'additionalProperties',
  optional(unknown())
);
