/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AdminConversationsRenameErrorEnum
 */
export enum AdminConversationsRenameErrorEnum {
  FeatureNotEnabled = 'feature_not_enabled',
  ChannelNotFound = 'channel_not_found',
  ChannelTypeNotSupported = 'channel_type_not_supported',
  RestrictedAction = 'restricted_action',
  CouldNotRenameChannel = 'could_not_rename_channel',
  DefaultOrgWideChannel = 'default_org_wide_channel',
  NameTaken = 'name_taken',
}

/**
 * Schema for AdminConversationsRenameErrorEnum
 */
export const adminConversationsRenameErrorEnumSchema: Schema<AdminConversationsRenameErrorEnum> = stringEnum(
  AdminConversationsRenameErrorEnum
);
