/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Prefs1, prefs1Schema } from './prefs1.js';

/** Schema for successful response of admin.conversations.getConversationPrefs */
export interface AdminConversationsGetConversationPrefsSchema {
  ok: string;
  prefs?: Prefs1;
  additionalProperties?: Record<string, unknown>;
}

export const adminConversationsGetConversationPrefsSchemaSchema: Schema<AdminConversationsGetConversationPrefsSchema> = lazy(
  () =>
    typedExpandoObject(
      { ok: ['ok', string()], prefs: ['prefs', optional(prefs1Schema)] },
      'additionalProperties',
      optional(unknown())
    )
);
