/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Generated from users.getPresence with shasum e7251aec575d8863f9e0eb38663ae9dc26655f65 */
export interface ApiMethodUsersGetPresence {
  autoAway?: boolean;
  connectionCount?: number;
  lastActivity?: number;
  manualAway?: boolean;
  ok: string;
  online?: boolean;
  presence: string;
  additionalProperties?: Record<string, unknown>;
}

export const apiMethodUsersGetPresenceSchema: Schema<ApiMethodUsersGetPresence> = typedExpandoObject(
  {
    autoAway: ['auto_away', optional(boolean())],
    connectionCount: ['connection_count', optional(number())],
    lastActivity: ['last_activity', optional(number())],
    manualAway: ['manual_away', optional(boolean())],
    ok: ['ok', string()],
    online: ['online', optional(boolean())],
    presence: ['presence', string()],
  },
  'additionalProperties',
  optional(unknown())
);
