/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Scopes, scopesSchema } from './scopes.js';

/** Schema for successful response api.permissions.scopes.list method */
export interface ApiPermissionsScopesListSuccessSchema {
  ok: string;
  scopes: Scopes;
  additionalProperties?: Record<string, unknown>;
}

export const apiPermissionsScopesListSuccessSchemaSchema: Schema<ApiPermissionsScopesListSuccessSchema> = lazy(
  () =>
    typedExpandoObject(
      { ok: ['ok', string()], scopes: ['scopes', scopesSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
