/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Info, infoSchema } from './info.js';

/** Schema for successful response from apps.permissions.info method */
export interface AppsPermissionsInfoSchema {
  info: Info;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export const appsPermissionsInfoSchemaSchema: Schema<AppsPermissionsInfoSchema> = lazy(
  () =>
    typedExpandoObject(
      { info: ['info', infoSchema], ok: ['ok', string()] },
      'additionalProperties',
      optional(unknown())
    )
);
