/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Resource, resourceSchema } from './resource.js';
import {
  ResponseMetadata,
  responseMetadataSchema,
} from './responseMetadata.js';

/** Schema for successful response apps.permissions.resources.list method */
export interface AppsPermissionsResourcesListSuccessSchema {
  ok: string;
  resources: Resource[];
  responseMetadata?: ResponseMetadata;
  additionalProperties?: Record<string, unknown>;
}

export const appsPermissionsResourcesListSuccessSchemaSchema: Schema<AppsPermissionsResourcesListSuccessSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        ok: ['ok', string()],
        resources: ['resources', array(resourceSchema)],
        responseMetadata: [
          'response_metadata',
          optional(responseMetadataSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
