/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AuthTestErrorEnum
 */
export enum AuthTestErrorEnum {
  NotAuthed = 'not_authed',
  InvalidAuth = 'invalid_auth',
  TokenRevoked = 'token_revoked',
  AccountInactive = 'account_inactive',
  InvalidArgName = 'invalid_arg_name',
  InvalidArrayArg = 'invalid_array_arg',
  InvalidCharset = 'invalid_charset',
  InvalidFormData = 'invalid_form_data',
  InvalidPostType = 'invalid_post_type',
  MissingPostType = 'missing_post_type',
  InvalidJson = 'invalid_json',
  JsonNotObject = 'json_not_object',
  RequestTimeout = 'request_timeout',
  UpgradeRequired = 'upgrade_required',
}

/**
 * Schema for AuthTestErrorEnum
 */
export const authTestErrorEnumSchema: Schema<AuthTestErrorEnum> = stringEnum(
  AuthTestErrorEnum
);
