/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response from auth.revoke method */
export interface AuthRevokeSchema {
  ok: string;
  revoked: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const authRevokeSchemaSchema: Schema<AuthRevokeSchema> = typedExpandoObject(
  { ok: ['ok', string()], revoked: ['revoked', boolean()] },
  'additionalProperties',
  optional(unknown())
);
