/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response auth.test method */
export interface AuthTestSuccessSchema {
  botId?: string;
  isEnterpriseInstall?: boolean;
  ok: string;
  team: string;
  teamId: string;
  url: string;
  user: string;
  userId: string;
  additionalProperties?: Record<string, unknown>;
}

export const authTestSuccessSchemaSchema: Schema<AuthTestSuccessSchema> = typedExpandoObject(
  {
    botId: ['bot_id', optional(string())],
    isEnterpriseInstall: ['is_enterprise_install', optional(boolean())],
    ok: ['ok', string()],
    team: ['team', string()],
    teamId: ['team_id', string()],
    url: ['url', string()],
    user: ['user', string()],
    userId: ['user_id', string()],
  },
  'additionalProperties',
  optional(unknown())
);
