/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface BlockKitBlock {
  type: string;
  additionalProperties?: Record<string, unknown>;
}

export const blockKitBlockSchema: Schema<BlockKitBlock> = typedExpandoObject(
  { type: ['type', string()] },
  'additionalProperties',
  optional(unknown())
);
