/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Icons, iconsSchema } from './icons.js';

export interface Bot {
  appId: string;
  deleted: boolean;
  icons: Icons;
  id: string;
  name: string;
  updated: number;
  userId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const botSchema: Schema<Bot> = lazy(() =>
  typedExpandoObject(
    {
      appId: ['app_id', string()],
      deleted: ['deleted', boolean()],
      icons: ['icons', iconsSchema],
      id: ['id', string()],
      name: ['name', string()],
      updated: ['updated', number()],
      userId: ['user_id', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
