/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ChatUpdateErrorEnum
 */
export enum ChatUpdateErrorEnum {
  MessageNotFound = 'message_not_found',
  CantUpdateMessage = 'cant_update_message',
  ChannelNotFound = 'channel_not_found',
  EditWindowClosed = 'edit_window_closed',
  MsgTooLong = 'msg_too_long',
  TooManyAttachments = 'too_many_attachments',
  RateLimited = 'rate_limited',
  NoText = 'no_text',
  NotAuthed = 'not_authed',
  InvalidAuth = 'invalid_auth',
  AccountInactive = 'account_inactive',
  TokenRevoked = 'token_revoked',
  NoPermission = 'no_permission',
  InvalidArgName = 'invalid_arg_name',
  InvalidArrayArg = 'invalid_array_arg',
  InvalidCharset = 'invalid_charset',
  InvalidFormData = 'invalid_form_data',
  InvalidPostType = 'invalid_post_type',
  MissingPostType = 'missing_post_type',
  RequestTimeout = 'request_timeout',
  InvalidJson = 'invalid_json',
  JsonNotObject = 'json_not_object',
  UpgradeRequired = 'upgrade_required',
  FatalError = 'fatal_error',
  IsInactive = 'is_inactive',
}

/**
 * Schema for ChatUpdateErrorEnum
 */
export const chatUpdateErrorEnumSchema: Schema<ChatUpdateErrorEnum> = stringEnum(
  ChatUpdateErrorEnum
);
