/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response from chat.meMessage method */
export interface ChatMeMessageSchema {
  channel?: string;
  ok: string;
  ts?: string;
  additionalProperties?: Record<string, unknown>;
}

export const chatMeMessageSchemaSchema: Schema<ChatMeMessageSchema> = typedExpandoObject(
  {
    channel: ['channel', optional(string())],
    ok: ['ok', string()],
    ts: ['ts', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
