/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MessageObject, messageObjectSchema } from './messageObject.js';

/** Schema for successful response of chat.postMessage method */
export interface ChatPostMessageSuccessSchema {
  channel: string;
  message: MessageObject;
  ok: string;
  ts: string;
  additionalProperties?: Record<string, unknown>;
}

export const chatPostMessageSuccessSchemaSchema: Schema<ChatPostMessageSuccessSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        channel: ['channel', string()],
        message: ['message', messageObjectSchema],
        ok: ['ok', string()],
        ts: ['ts', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
