/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response from chat.postEphemeral method */
export interface ChatPostEphemeralSuccessSchema {
  messageTs: string;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export const chatPostEphemeralSuccessSchemaSchema: Schema<ChatPostEphemeralSuccessSchema> = typedExpandoObject(
  { messageTs: ['message_ts', string()], ok: ['ok', string()] },
  'additionalProperties',
  optional(unknown())
);
