/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response chat.getPermalink */
export interface ChatGetPermalinkSuccessSchema {
  channel: string;
  ok: string;
  permalink: string;
  additionalProperties?: Record<string, unknown>;
}

export const chatGetPermalinkSuccessSchemaSchema: Schema<ChatGetPermalinkSuccessSchema> = typedExpandoObject(
  {
    channel: ['channel', string()],
    ok: ['ok', string()],
    permalink: ['permalink', string()],
  },
  'additionalProperties',
  optional(unknown())
);
