/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Message, messageSchema } from './message.js';

/** Schema for successful response of chat.scheduleMessage method */
export interface ChatScheduleMessageSuccessSchema {
  channel: string;
  message: Message;
  ok: string;
  postAt: number;
  scheduledMessageId: string;
  additionalProperties?: Record<string, unknown>;
}

export const chatScheduleMessageSuccessSchemaSchema: Schema<ChatScheduleMessageSuccessSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        channel: ['channel', string()],
        message: ['message', messageSchema],
        ok: ['ok', string()],
        postAt: ['post_at', number()],
        scheduledMessageId: ['scheduled_message_id', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
