/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response of chat.delete method */
export interface ChatDeleteSuccessSchema {
  channel: string;
  ok: string;
  ts: string;
  additionalProperties?: Record<string, unknown>;
}

export const chatDeleteSuccessSchemaSchema: Schema<ChatDeleteSuccessSchema> = typedExpandoObject(
  {
    channel: ['channel', string()],
    ok: ['ok', string()],
    ts: ['ts', string()],
  },
  'additionalProperties',
  optional(unknown())
);
