/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ConversationsInviteErrorEnum
 */
export enum ConversationsInviteErrorEnum {
  MethodNotSupportedForChannelType = 'method_not_supported_for_channel_type',
  MissingScope = 'missing_scope',
  ChannelNotFound = 'channel_not_found',
  UserNotFound = 'user_not_found',
  NoUser = 'no_user',
  CantInviteSelf = 'cant_invite_self',
  NotInChannel = 'not_in_channel',
  AlreadyInChannel = 'already_in_channel',
  IsArchived = 'is_archived',
  CantInvite = 'cant_invite',
  TooManyUsers = 'too_many_users',
  UraMaxChannels = 'ura_max_channels',
  NotAuthed = 'not_authed',
  InvalidAuth = 'invalid_auth',
  AccountInactive = 'account_inactive',
  UserIsBot = 'user_is_bot',
  UserIsRestricted = 'user_is_restricted',
  UserIsUltraRestricted = 'user_is_ultra_restricted',
  InvalidArgName = 'invalid_arg_name',
  InvalidArrayArg = 'invalid_array_arg',
  InvalidCharset = 'invalid_charset',
  InvalidFormData = 'invalid_form_data',
  InvalidPostType = 'invalid_post_type',
  MissingPostType = 'missing_post_type',
  InvalidJson = 'invalid_json',
  JsonNotObject = 'json_not_object',
  RequestTimeout = 'request_timeout',
  UpgradeRequired = 'upgrade_required',
  TeamAddedToOrg = 'team_added_to_org',
  MissingCharset = 'missing_charset',
  SuperfluousCharset = 'superfluous_charset',
}

/**
 * Schema for ConversationsInviteErrorEnum
 */
export const conversationsInviteErrorEnumSchema: Schema<ConversationsInviteErrorEnum> = stringEnum(
  ConversationsInviteErrorEnum
);
