/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response conversations.create method */
export interface ConversationsCreateSuccessSchema {
  channel?: unknown;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export const conversationsCreateSuccessSchemaSchema: Schema<ConversationsCreateSuccessSchema> = typedExpandoObject(
  { channel: ['channel', optional(unknown())], ok: ['ok', string()] },
  'additionalProperties',
  optional(unknown())
);
