/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response from conversations.open method when opening channels, ims, mpims */
export interface ConversationsOpenSuccessSchema {
  alreadyOpen?: boolean;
  channel?: unknown;
  noOp?: boolean;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export const conversationsOpenSuccessSchemaSchema: Schema<ConversationsOpenSuccessSchema> = typedExpandoObject(
  {
    alreadyOpen: ['already_open', optional(boolean())],
    channel: ['channel', optional(unknown())],
    noOp: ['no_op', optional(boolean())],
    ok: ['ok', string()],
  },
  'additionalProperties',
  optional(unknown())
);
