/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response conversations.close method */
export interface ConversationsCloseSuccessSchema {
  alreadyClosed?: boolean;
  noOp?: boolean;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export const conversationsCloseSuccessSchemaSchema: Schema<ConversationsCloseSuccessSchema> = typedExpandoObject(
  {
    alreadyClosed: ['already_closed', optional(boolean())],
    noOp: ['no_op', optional(boolean())],
    ok: ['ok', string()],
  },
  'additionalProperties',
  optional(unknown())
);
