/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MessageObject, messageObjectSchema } from './messageObject.js';

/** Schema for successful response from conversations.history method */
export interface ConversationsHistorySuccessSchema {
  channelActionsCount: number;
  channelActionsTs?: unknown;
  hasMore: boolean;
  messages: MessageObject[];
  ok: string;
  pinCount: number;
  additionalProperties?: Record<string, unknown>;
}

export const conversationsHistorySuccessSchemaSchema: Schema<ConversationsHistorySuccessSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        channelActionsCount: ['channel_actions_count', number()],
        channelActionsTs: ['channel_actions_ts', optional(unknown())],
        hasMore: ['has_more', boolean()],
        messages: ['messages', array(messageObjectSchema)],
        ok: ['ok', string()],
        pinCount: ['pin_count', number()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
