/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ConversationsCloseErrorEnum
 */
export enum ConversationsCloseErrorEnum {
  MethodNotSupportedForChannelType = 'method_not_supported_for_channel_type',
  ChannelNotFound = 'channel_not_found',
  UserDoesNotOwnChannel = 'user_does_not_own_channel',
  MissingScope = 'missing_scope',
  NotAuthed = 'not_authed',
  InvalidAuth = 'invalid_auth',
  AccountInactive = 'account_inactive',
  InvalidArgName = 'invalid_arg_name',
  InvalidArrayArg = 'invalid_array_arg',
  InvalidCharset = 'invalid_charset',
  InvalidFormData = 'invalid_form_data',
  InvalidPostType = 'invalid_post_type',
  MissingPostType = 'missing_post_type',
  TeamAddedToOrg = 'team_added_to_org',
  InvalidJson = 'invalid_json',
  JsonNotObject = 'json_not_object',
  RequestTimeout = 'request_timeout',
  UpgradeRequired = 'upgrade_required',
}

/**
 * Schema for ConversationsCloseErrorEnum
 */
export const conversationsCloseErrorEnumSchema: Schema<ConversationsCloseErrorEnum> = stringEnum(
  ConversationsCloseErrorEnum
);
