/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseMetadata,
  responseMetadataSchema,
} from './responseMetadata.js';

/** Schema for successful response conversations.members method */
export interface ConversationsMembersSuccessSchema {
  members: string[];
  ok: string;
  responseMetadata: ResponseMetadata;
  additionalProperties?: Record<string, unknown>;
}

export const conversationsMembersSuccessSchemaSchema: Schema<ConversationsMembersSuccessSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        members: ['members', array(string())],
        ok: ['ok', string()],
        responseMetadata: ['response_metadata', responseMetadataSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
