/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResponseMetadata,
  responseMetadataSchema,
} from './responseMetadata.js';

/** Schema for successful response from conversations.list method */
export interface ConversationsListSuccessSchema {
  channels: unknown[];
  ok: string;
  responseMetadata?: ResponseMetadata;
  additionalProperties?: Record<string, unknown>;
}

export const conversationsListSuccessSchemaSchema: Schema<ConversationsListSuccessSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        channels: ['channels', array(unknown())],
        ok: ['ok', string()],
        responseMetadata: [
          'response_metadata',
          optional(responseMetadataSchema),
        ],
      },
      'additionalProperties',
      optional(unknown())
    )
);
