/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response conversations.archive method */
export interface ConversationsArchiveSuccessSchema {
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export const conversationsArchiveSuccessSchemaSchema: Schema<ConversationsArchiveSuccessSchema> = typedExpandoObject(
  { ok: ['ok', string()] },
  'additionalProperties',
  optional(unknown())
);
