/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Current {
  dateStarted: number;
  teamId: string;
  additionalProperties?: Record<string, unknown>;
}

export const currentSchema: Schema<Current> = typedExpandoObject(
  { dateStarted: ['date_started', number()], teamId: ['team_id', string()] },
  'additionalProperties',
  optional(unknown())
);
