/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** This method either only returns a brief _OK_ response or a verbose schema is not available for this method. */
export interface DefaultSuccessTemplate {
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export const defaultSuccessTemplateSchema: Schema<DefaultSuccessTemplate> = typedExpandoObject(
  { ok: ['ok', string()] },
  'additionalProperties',
  optional(unknown())
);
