/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response from dnd.endSnooze method */
export interface DndEndSnoozeSchema {
  dndEnabled: boolean;
  nextDndEndTs: number;
  nextDndStartTs: number;
  ok: string;
  snoozeEnabled: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const dndEndSnoozeSchemaSchema: Schema<DndEndSnoozeSchema> = typedExpandoObject(
  {
    dndEnabled: ['dnd_enabled', boolean()],
    nextDndEndTs: ['next_dnd_end_ts', number()],
    nextDndStartTs: ['next_dnd_start_ts', number()],
    ok: ['ok', string()],
    snoozeEnabled: ['snooze_enabled', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
