/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response from dnd.info method */
export interface DndInfoSchema {
  dndEnabled: boolean;
  nextDndEndTs: number;
  nextDndStartTs: number;
  ok: string;
  snoozeEnabled?: boolean;
  snoozeEndtime?: number;
  snoozeRemaining?: number;
  additionalProperties?: Record<string, unknown>;
}

export const dndInfoSchemaSchema: Schema<DndInfoSchema> = typedExpandoObject(
  {
    dndEnabled: ['dnd_enabled', boolean()],
    nextDndEndTs: ['next_dnd_end_ts', number()],
    nextDndStartTs: ['next_dnd_start_ts', number()],
    ok: ['ok', string()],
    snoozeEnabled: ['snooze_enabled', optional(boolean())],
    snoozeEndtime: ['snooze_endtime', optional(number())],
    snoozeRemaining: ['snooze_remaining', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
