/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Error7
 */
export enum Error7 {
  FeatureNotEnabled = 'feature_not_enabled',
  ChannelNotFound = 'channel_not_found',
  ChannelTypeNotSupported = 'channel_type_not_supported',
  DefaultOrgWideChannel = 'default_org_wide_channel',
  RestrictedAction = 'restricted_action',
  UserMustBeAdmin = 'user_must_be_admin',
  FailedForSomeUsers = 'failed_for_some_users',
}

/**
 * Schema for Error7
 */
export const error7Schema: Schema<Error7> = stringEnum(Error7);
