/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Error
 */
export enum Error {
  FeatureNotEnabled = 'feature_not_enabled',
  ChannelNotFound = 'channel_not_found',
  ChannelTypeNotSupported = 'channel_type_not_supported',
  DefaultOrgWideChannel = 'default_org_wide_channel',
  AlreadyArchived = 'already_archived',
  CantArchiveGeneral = 'cant_archive_general',
  RestrictedAction = 'restricted_action',
  CouldNotArchiveChannel = 'could_not_archive_channel',
}

/**
 * Schema for Error
 */
export const errorSchema: Schema<Error> = stringEnum(Error);
