/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Error9
 */
export enum Error9 {
  FeatureNotEnabled = 'feature_not_enabled',
  NotAnAdmin = 'not_an_admin',
  NotAnEnterprise = 'not_an_enterprise',
  TeamNotFound = 'team_not_found',
  NotAllowed = 'not_allowed',
  InvalidAuth = 'invalid_auth',
  InvalidCursor = 'invalid_cursor',
  InvalidSearchChannelType = 'invalid_search_channel_type',
  InvalidSort = 'invalid_sort',
  InvalidSortDir = 'invalid_sort_dir',
}

/**
 * Schema for Error9
 */
export const error9Schema: Schema<Error9> = stringEnum(Error9);
