/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Error5
 */
export enum Error5 {
  FeatureNotEnabled = 'feature_not_enabled',
  NotAnAdmin = 'not_an_admin',
  NotAnEnterprise = 'not_an_enterprise',
  RestrictedAction = 'restricted_action',
  MissingScope = 'missing_scope',
  ChannelNotFound = 'channel_not_found',
  ChannelTypeNotSupported = 'channel_type_not_supported',
  CouldNotGetConversationPrefs = 'could_not_get_conversation_prefs',
}

/**
 * Schema for Error5
 */
export const error5Schema: Schema<Error5> = stringEnum(Error5);
