/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Error35, error35Schema } from './error35.js';

export interface ErrorsIsReturnedWhenAnErrorAssociatesAnUser {
  error: Error35;
  ok: string;
  user?: string;
  additionalProperties?: Record<string, unknown>;
}

export const errorsIsReturnedWhenAnErrorAssociatesAnUserSchema: Schema<ErrorsIsReturnedWhenAnErrorAssociatesAnUser> = typedExpandoObject(
  {
    error: ['error', error35Schema],
    ok: ['ok', string()],
    user: ['user', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
