/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Error43
 */
export enum Error43 {
  MethodNotSupportedForChannelType = 'method_not_supported_for_channel_type',
  UserNotFound = 'user_not_found',
  UserNotVisible = 'user_not_visible',
  UserDisabled = 'user_disabled',
  UsersListNotSupplied = 'users_list_not_supplied',
  NotEnoughUsers = 'not_enough_users',
  TooManyUsers = 'too_many_users',
  InvalidUserCombination = 'invalid_user_combination',
  NotAuthed = 'not_authed',
  InvalidAuth = 'invalid_auth',
  AccountInactive = 'account_inactive',
  InvalidArgName = 'invalid_arg_name',
  InvalidArrayArg = 'invalid_array_arg',
  InvalidCharset = 'invalid_charset',
  InvalidFormData = 'invalid_form_data',
  InvalidPostType = 'invalid_post_type',
  MissingPostType = 'missing_post_type',
  TeamAddedToOrg = 'team_added_to_org',
  InvalidJson = 'invalid_json',
  JsonNotObject = 'json_not_object',
  RequestTimeout = 'request_timeout',
  UpgradeRequired = 'upgrade_required',
  ChannelNotFound = 'channel_not_found',
}

/**
 * Schema for Error43
 */
export const error43Schema: Schema<Error43> = stringEnum(Error43);
