/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Error25
 */
export enum Error25 {
  ChannelNotFound = 'channel_not_found',
  NotInChannel = 'not_in_channel',
  IsArchived = 'is_archived',
  MsgTooLong = 'msg_too_long',
  NoText = 'no_text',
  TooManyAttachments = 'too_many_attachments',
  RateLimited = 'rate_limited',
  NotAuthed = 'not_authed',
  InvalidAuth = 'invalid_auth',
  AccountInactive = 'account_inactive',
  InvalidArgName = 'invalid_arg_name',
  InvalidArrayArg = 'invalid_array_arg',
  InvalidCharset = 'invalid_charset',
  InvalidFormData = 'invalid_form_data',
  InvalidPostType = 'invalid_post_type',
  MissingPostType = 'missing_post_type',
}

/**
 * Schema for Error25
 */
export const error25Schema: Schema<Error25> = stringEnum(Error25);
