/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Error49
 */
export enum Error49 {
  ValidationErrors = 'validation_errors',
  MissingTrigger = 'missing_trigger',
  MissingDialog = 'missing_dialog',
  TriggerExchanged = 'trigger_exchanged',
  TriggerExpired = 'trigger_expired',
  InvalidTrigger = 'invalid_trigger',
  AppMissingActionUrl = 'app_missing_action_url',
  CannotCreateDialog = 'cannot_create_dialog',
  FailedSendingDialog = 'failed_sending_dialog',
  NotAuthed = 'not_authed',
  InvalidAuth = 'invalid_auth',
  AccountInactive = 'account_inactive',
  TokenRevoked = 'token_revoked',
  NoPermission = 'no_permission',
  OrgLoginRequired = 'org_login_required',
  InvalidArgName = 'invalid_arg_name',
  InvalidArrayArg = 'invalid_array_arg',
  InvalidCharset = 'invalid_charset',
  InvalidFormData = 'invalid_form_data',
  InvalidPostType = 'invalid_post_type',
  MissingPostType = 'missing_post_type',
  TeamAddedToOrg = 'team_added_to_org',
  InvalidJson = 'invalid_json',
  JsonNotObject = 'json_not_object',
  RequestTimeout = 'request_timeout',
  UpgradeRequired = 'upgrade_required',
  FatalError = 'fatal_error',
}

/**
 * Schema for Error49
 */
export const error49Schema: Schema<Error49> = stringEnum(Error49);
