/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Error4
 */
export enum Error4 {
  FeatureNotEnabled = 'feature_not_enabled',
  NotAnAdmin = 'not_an_admin',
  NotAnEnterprise = 'not_an_enterprise',
  ChannelNotFound = 'channel_not_found',
  NotSupported = 'not_supported',
  TeamNotFound = 'team_not_found',
  RestrictedAction = 'restricted_action',
  MissingScope = 'missing_scope',
  LeavingTeamNotInChannel = 'leaving_team_not_in_channel',
  NoTeamsToDisconnect = 'no_teams_to_disconnect',
  LeavingTeamRequired = 'leaving_team_required',
  CannotKickTeam = 'cannot_kick_team',
  CannotKickHomeTeam = 'cannot_kick_home_team',
}

/**
 * Schema for Error4
 */
export const error4Schema: Schema<Error4> = stringEnum(Error4);
