/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Error6
 */
export enum Error6 {
  FeatureNotEnabled = 'feature_not_enabled',
  ChannelNotFound = 'channel_not_found',
  ChannelTypeNotSupported = 'channel_type_not_supported',
  UnsupportedTeamType = 'unsupported_team_type',
  RestrictedAction = 'restricted_action',
  CouldNotGetTeams = 'could_not_get_teams',
  InvalidCursor = 'invalid_cursor',
  InvalidLimit = 'invalid_limit',
}

/**
 * Schema for Error6
 */
export const error6Schema: Schema<Error6> = stringEnum(Error6);
