/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Current, currentSchema } from './current.js';

export interface ExternalOrgMigrations {
  current: Current[];
  dateUpdated: number;
  additionalProperties?: Record<string, unknown>;
}

export const externalOrgMigrationsSchema: Schema<ExternalOrgMigrations> = lazy(
  () =>
    typedExpandoObject(
      {
        current: ['current', array(currentSchema)],
        dateUpdated: ['date_updated', number()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
