/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FileObject, fileObjectSchema } from './fileObject.js';
import { PagingObject, pagingObjectSchema } from './pagingObject.js';

/** Schema for successful response from files.info method */
export interface FilesInfoSchema {
  comments: unknown[];
  contentHtml?: string | null;
  editor?: string;
  file: FileObject;
  ok: string;
  paging?: PagingObject;
  responseMetadata?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const filesInfoSchemaSchema: Schema<FilesInfoSchema> = lazy(() =>
  typedExpandoObject(
    {
      comments: ['comments', array(unknown())],
      contentHtml: ['content_html', optional(nullable(string()))],
      editor: ['editor', optional(string())],
      file: ['file', fileObjectSchema],
      ok: ['ok', string()],
      paging: ['paging', optional(pagingObjectSchema)],
      responseMetadata: ['response_metadata', optional(unknown())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
