/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FileObject, fileObjectSchema } from './fileObject.js';
import { PagingObject, pagingObjectSchema } from './pagingObject.js';

/** Schema for successful response from files.list method */
export interface FilesListSchema {
  files: FileObject[];
  ok: string;
  paging: PagingObject;
  additionalProperties?: Record<string, unknown>;
}

export const filesListSchemaSchema: Schema<FilesListSchema> = lazy(() =>
  typedExpandoObject(
    {
      files: ['files', array(fileObjectSchema)],
      ok: ['ok', string()],
      paging: ['paging', pagingObjectSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
