/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FileObject, fileObjectSchema } from './fileObject.js';

/** Schema for successful response from files.sharedPublicURL method */
export interface FilesSharedPublicUrlSchema {
  file: FileObject;
  ok: string;
  additionalProperties?: Record<string, unknown>;
}

export const filesSharedPublicUrlSchemaSchema: Schema<FilesSharedPublicUrlSchema> = lazy(
  () =>
    typedExpandoObject(
      { file: ['file', fileObjectSchema], ok: ['ok', string()] },
      'additionalProperties',
      optional(unknown())
    )
);
