/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ReactionObject, reactionObjectSchema } from './reactionObject.js';

export interface FileCommentObject {
  comment: string;
  created: number;
  id: string;
  isIntro: boolean;
  isStarred?: boolean;
  numStars?: number;
  pinnedInfo?: unknown;
  pinnedTo?: string[];
  reactions?: ReactionObject[];
  timestamp: number;
  user: string;
  additionalProperties?: Record<string, unknown>;
}

export const fileCommentObjectSchema: Schema<FileCommentObject> = lazy(() =>
  typedExpandoObject(
    {
      comment: ['comment', string()],
      created: ['created', number()],
      id: ['id', string()],
      isIntro: ['is_intro', boolean()],
      isStarred: ['is_starred', optional(boolean())],
      numStars: ['num_stars', optional(number())],
      pinnedInfo: ['pinned_info', optional(unknown())],
      pinnedTo: ['pinned_to', optional(array(string()))],
      reactions: ['reactions', optional(array(reactionObjectSchema))],
      timestamp: ['timestamp', number()],
      user: ['user', string()],
    },
    'additionalProperties',
    optional(unknown())
  )
);
