/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ResourcesInInfoFromAppsPermissionsInfo,
  resourcesInInfoFromAppsPermissionsInfoSchema,
} from './resourcesInInfoFromAppsPermissionsInfo.js';

export interface Group {
  resources?: ResourcesInInfoFromAppsPermissionsInfo;
  scopes?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const groupSchema: Schema<Group> = lazy(() =>
  typedExpandoObject(
    {
      resources: [
        'resources',
        optional(resourcesInInfoFromAppsPermissionsInfoSchema),
      ],
      scopes: ['scopes', optional(array(string()))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
