/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Icons1 {
  emoji?: string;
  image64?: string;
  additionalProperties?: Record<string, unknown>;
}

export const icons1Schema: Schema<Icons1> = typedExpandoObject(
  {
    emoji: ['emoji', optional(string())],
    image64: ['image_64', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
