/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AppHome, appHomeSchema } from './appHome.js';
import { Channel, channelSchema } from './channel.js';
import { Group, groupSchema } from './group.js';
import { Im, imSchema } from './im.js';
import { Mpim, mpimSchema } from './mpim.js';
import { Team, teamSchema } from './team.js';

export interface Info {
  appHome: AppHome;
  channel: Channel;
  group: Group;
  im: Im;
  mpim: Mpim;
  team: Team;
  additionalProperties?: Record<string, unknown>;
}

export const infoSchema: Schema<Info> = lazy(() =>
  typedExpandoObject(
    {
      appHome: ['app_home', appHomeSchema],
      channel: ['channel', channelSchema],
      group: ['group', groupSchema],
      im: ['im', imSchema],
      mpim: ['mpim', mpimSchema],
      team: ['team', teamSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
