/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Log {
  adminAppId?: string;
  appId: string;
  appType: string;
  changeType: string;
  channel?: string;
  date: string;
  scope: string;
  serviceId?: string;
  serviceType?: string;
  userId: string;
  userName: string;
  additionalProperties?: Record<string, unknown>;
}

export const logSchema: Schema<Log> = typedExpandoObject(
  {
    adminAppId: ['admin_app_id', optional(string())],
    appId: ['app_id', string()],
    appType: ['app_type', string()],
    changeType: ['change_type', string()],
    channel: ['channel', optional(string())],
    date: ['date', string()],
    scope: ['scope', string()],
    serviceId: ['service_id', optional(string())],
    serviceType: ['service_type', optional(string())],
    userId: ['user_id', string()],
    userName: ['user_name', string()],
  },
  'additionalProperties',
  optional(unknown())
);
