/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Login {
  count: number;
  country: string | null;
  dateFirst: number;
  dateLast: number;
  ip: string | null;
  isp: string | null;
  region: string | null;
  userAgent: string;
  userId: string;
  username: string;
  additionalProperties?: Record<string, unknown>;
}

export const loginSchema: Schema<Login> = typedExpandoObject(
  {
    count: ['count', number()],
    country: ['country', nullable(string())],
    dateFirst: ['date_first', number()],
    dateLast: ['date_last', number()],
    ip: ['ip', nullable(string())],
    isp: ['isp', nullable(string())],
    region: ['region', nullable(string())],
    userAgent: ['user_agent', string()],
    userId: ['user_id', string()],
    username: ['username', string()],
  },
  'additionalProperties',
  optional(unknown())
);
