/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  BotProfileObject,
  botProfileObjectSchema,
} from './botProfileObject.js';

export interface Message {
  botId: string;
  botProfile?: BotProfileObject;
  team: string;
  text: string;
  type: string;
  user: string;
  username?: string;
  additionalProperties?: Record<string, unknown>;
}

export const messageSchema: Schema<Message> = lazy(() =>
  typedExpandoObject(
    {
      botId: ['bot_id', string()],
      botProfile: ['bot_profile', optional(botProfileObjectSchema)],
      team: ['team', string()],
      text: ['text', string()],
      type: ['type', string()],
      user: ['user', string()],
      username: ['username', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
