/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Attachment, attachmentSchema } from './attachment.js';
import { BlockKitBlock, blockKitBlockSchema } from './blockKitBlock.js';
import {
  BotProfileObject,
  botProfileObjectSchema,
} from './botProfileObject.js';
import {
  FileCommentObject,
  fileCommentObjectSchema,
} from './fileCommentObject.js';
import { FileObject, fileObjectSchema } from './fileObject.js';
import { Icons1, icons1Schema } from './icons1.js';
import {
  ObjsUserProfileShort,
  objsUserProfileShortSchema,
} from './objsUserProfileShort.js';
import { ReactionObject, reactionObjectSchema } from './reactionObject.js';

export interface MessageObject {
  attachments?: Attachment[];
  /** This is a very loose definition, in the future, we'll populate this with deeper schema in this definition namespace. */
  blocks?: BlockKitBlock[];
  botId?: unknown;
  botProfile?: BotProfileObject;
  clientMsgId?: string;
  comment?: FileCommentObject;
  displayAsBot?: boolean;
  file?: FileObject;
  files?: FileObject[];
  icons?: Icons1;
  inviter?: string;
  isDelayedMessage?: boolean;
  isIntro?: boolean;
  isStarred?: boolean;
  lastRead?: string;
  latestReply?: string;
  name?: string;
  oldName?: string;
  parentUserId?: string;
  permalink?: string;
  pinnedTo?: string[];
  purpose?: string;
  reactions?: ReactionObject[];
  replyCount?: number;
  replyUsers?: string[];
  replyUsersCount?: number;
  sourceTeam?: string;
  subscribed?: boolean;
  subtype?: string;
  team?: string;
  text: string;
  threadTs?: string;
  topic?: string;
  ts: string;
  type: string;
  unreadCount?: number;
  upload?: boolean;
  user?: string;
  userProfile?: ObjsUserProfileShort;
  userTeam?: string;
  username?: string;
  additionalProperties?: Record<string, unknown>;
}

export const messageObjectSchema: Schema<MessageObject> = lazy(() =>
  typedExpandoObject(
    {
      attachments: ['attachments', optional(array(attachmentSchema))],
      blocks: ['blocks', optional(array(blockKitBlockSchema))],
      botId: ['bot_id', optional(unknown())],
      botProfile: ['bot_profile', optional(botProfileObjectSchema)],
      clientMsgId: ['client_msg_id', optional(string())],
      comment: ['comment', optional(fileCommentObjectSchema)],
      displayAsBot: ['display_as_bot', optional(boolean())],
      file: ['file', optional(fileObjectSchema)],
      files: ['files', optional(array(fileObjectSchema))],
      icons: ['icons', optional(icons1Schema)],
      inviter: ['inviter', optional(string())],
      isDelayedMessage: ['is_delayed_message', optional(boolean())],
      isIntro: ['is_intro', optional(boolean())],
      isStarred: ['is_starred', optional(boolean())],
      lastRead: ['last_read', optional(string())],
      latestReply: ['latest_reply', optional(string())],
      name: ['name', optional(string())],
      oldName: ['old_name', optional(string())],
      parentUserId: ['parent_user_id', optional(string())],
      permalink: ['permalink', optional(string())],
      pinnedTo: ['pinned_to', optional(array(string()))],
      purpose: ['purpose', optional(string())],
      reactions: ['reactions', optional(array(reactionObjectSchema))],
      replyCount: ['reply_count', optional(number())],
      replyUsers: ['reply_users', optional(array(string()))],
      replyUsersCount: ['reply_users_count', optional(number())],
      sourceTeam: ['source_team', optional(string())],
      subscribed: ['subscribed', optional(boolean())],
      subtype: ['subtype', optional(string())],
      team: ['team', optional(string())],
      text: ['text', string()],
      threadTs: ['thread_ts', optional(string())],
      topic: ['topic', optional(string())],
      ts: ['ts', string()],
      type: ['type', string()],
      unreadCount: ['unread_count', optional(number())],
      upload: ['upload', optional(boolean())],
      user: ['user', optional(string())],
      userProfile: ['user_profile', optional(objsUserProfileShortSchema)],
      userTeam: ['user_team', optional(string())],
      username: ['username', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
