/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response from migration.exchange method */
export interface MigrationExchangeSuccessSchema {
  enterpriseId: string;
  invalidUserIds?: string[];
  ok: string;
  teamId: string;
  userIdMap?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const migrationExchangeSuccessSchemaSchema: Schema<MigrationExchangeSuccessSchema> = typedExpandoObject(
  {
    enterpriseId: ['enterprise_id', string()],
    invalidUserIds: ['invalid_user_ids', optional(array(string()))],
    ok: ['ok', string()],
    teamId: ['team_id', string()],
    userIdMap: ['user_id_map', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
