/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ObjsReminder {
  completeTs?: number;
  creator: string;
  id: string;
  recurring: boolean;
  text: string;
  time?: number;
  user: string;
  additionalProperties?: Record<string, unknown>;
}

export const objsReminderSchema: Schema<ObjsReminder> = typedExpandoObject(
  {
    completeTs: ['complete_ts', optional(number())],
    creator: ['creator', string()],
    id: ['id', string()],
    recurring: ['recurring', boolean()],
    text: ['text', string()],
    time: ['time', optional(number())],
    user: ['user', string()],
  },
  'additionalProperties',
  optional(unknown())
);
