/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ObjsUserProfileShort {
  avatarHash: string;
  displayName: string;
  displayNameNormalized?: string;
  firstName: string | null;
  image72: string;
  isRestricted: boolean;
  isUltraRestricted: boolean;
  name: string;
  realName: string;
  realNameNormalized?: string;
  team: string;
  additionalProperties?: Record<string, unknown>;
}

export const objsUserProfileShortSchema: Schema<ObjsUserProfileShort> = typedExpandoObject(
  {
    avatarHash: ['avatar_hash', string()],
    displayName: ['display_name', string()],
    displayNameNormalized: ['display_name_normalized', optional(string())],
    firstName: ['first_name', nullable(string())],
    image72: ['image_72', string()],
    isRestricted: ['is_restricted', boolean()],
    isUltraRestricted: ['is_ultra_restricted', boolean()],
    name: ['name', string()],
    realName: ['real_name', string()],
    realNameNormalized: ['real_name_normalized', optional(string())],
    team: ['team', string()],
  },
  'additionalProperties',
  optional(unknown())
);
