/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ObjsPrimaryOwner {
  email: string;
  id: string;
  additionalProperties?: Record<string, unknown>;
}

export const objsPrimaryOwnerSchema: Schema<ObjsPrimaryOwner> = typedExpandoObject(
  { email: ['email', string()], id: ['id', string()] },
  'additionalProperties',
  optional(unknown())
);
