/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ObjsIcon {
  image102?: string;
  image132?: string;
  image230?: string;
  image34?: string;
  image44?: string;
  image68?: string;
  image88?: string;
  imageDefault?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const objsIconSchema: Schema<ObjsIcon> = typedExpandoObject(
  {
    image102: ['image_102', optional(string())],
    image132: ['image_132', optional(string())],
    image230: ['image_230', optional(string())],
    image34: ['image_34', optional(string())],
    image44: ['image_44', optional(string())],
    image68: ['image_68', optional(string())],
    image88: ['image_88', optional(string())],
    imageDefault: ['image_default', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
