/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PagingObject {
  count?: number;
  page: number;
  pages?: number;
  perPage?: number;
  spill?: number;
  total: number;
  additionalProperties?: Record<string, unknown>;
}

export const pagingObjectSchema: Schema<PagingObject> = typedExpandoObject(
  {
    count: ['count', optional(number())],
    page: ['page', number()],
    pages: ['pages', optional(number())],
    perPage: ['per_page', optional(number())],
    spill: ['spill', optional(number())],
    total: ['total', number()],
  },
  'additionalProperties',
  optional(unknown())
);
