/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Plan
 */
export enum Plan {
  Std = 'std',
  Plus = 'plus',
  Compliance = 'compliance',
  Enterprise = 'enterprise',
}

/**
 * Schema for Plan
 */
export const planSchema: Schema<Plan> = stringEnum(Plan);
