/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CanThread, canThreadSchema } from './canThread.js';
import { WhoCanPost, whoCanPostSchema } from './whoCanPost.js';

export interface Prefs1 {
  canThread?: CanThread;
  whoCanPost?: WhoCanPost;
  additionalProperties?: Record<string, unknown>;
}

export const prefs1Schema: Schema<Prefs1> = lazy(() =>
  typedExpandoObject(
    {
      canThread: ['can_thread', optional(canThreadSchema)],
      whoCanPost: ['who_can_post', optional(whoCanPostSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
