/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Prefs {
  channels: string[];
  groups: string[];
  additionalProperties?: Record<string, unknown>;
}

export const prefsSchema: Schema<Prefs> = typedExpandoObject(
  {
    channels: ['channels', array(string())],
    groups: ['groups', array(string())],
  },
  'additionalProperties',
  optional(unknown())
);
