/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ObjsTeamProfileField,
  objsTeamProfileFieldSchema,
} from './objsTeamProfileField.js';

export interface Profile {
  fields: ObjsTeamProfileField[];
  additionalProperties?: Record<string, unknown>;
}

export const profileSchema: Schema<Profile> = lazy(() =>
  typedExpandoObject(
    { fields: ['fields', array(objsTeamProfileFieldSchema)] },
    'additionalProperties',
    optional(unknown())
  )
);
