/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ReactionsGetErrorEnum
 */
export enum ReactionsGetErrorEnum {
  BadTimestamp = 'bad_timestamp',
  FileNotFound = 'file_not_found',
  FileCommentNotFound = 'file_comment_not_found',
  MessageNotFound = 'message_not_found',
  NoItemSpecified = 'no_item_specified',
  NotAuthed = 'not_authed',
  InvalidAuth = 'invalid_auth',
  AccountInactive = 'account_inactive',
  NoPermission = 'no_permission',
  InvalidArrayArg = 'invalid_array_arg',
  InvalidCharset = 'invalid_charset',
  InvalidFormData = 'invalid_form_data',
  InvalidPostType = 'invalid_post_type',
  MissingPostType = 'missing_post_type',
  TeamAddedToOrg = 'team_added_to_org',
  InvalidJson = 'invalid_json',
  JsonNotObject = 'json_not_object',
  RequestTimeout = 'request_timeout',
  UpgradeRequired = 'upgrade_required',
}

/**
 * Schema for ReactionsGetErrorEnum
 */
export const reactionsGetErrorEnumSchema: Schema<ReactionsGetErrorEnum> = stringEnum(
  ReactionsGetErrorEnum
);
