/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { PagingObject, pagingObjectSchema } from './pagingObject.js';

/** Schema for successful response from reactions.list method */
export interface ReactionsListSchema {
  items: unknown[];
  ok: string;
  paging?: PagingObject;
  responseMetadata?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const reactionsListSchemaSchema: Schema<ReactionsListSchema> = lazy(() =>
  typedExpandoObject(
    {
      items: ['items', array(unknown())],
      ok: ['ok', string()],
      paging: ['paging', optional(pagingObjectSchema)],
      responseMetadata: ['response_metadata', optional(unknown())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
