/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ObjsReminder, objsReminderSchema } from './objsReminder.js';

/** Schema for successful response from reminders.add method */
export interface RemindersAddSchema {
  ok: string;
  reminder: ObjsReminder;
  additionalProperties?: Record<string, unknown>;
}

export const remindersAddSchemaSchema: Schema<RemindersAddSchema> = lazy(() =>
  typedExpandoObject(
    { ok: ['ok', string()], reminder: ['reminder', objsReminderSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
