/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Resource {
  id?: string;
  type?: string;
  additionalProperties?: Record<string, unknown>;
}

export const resourceSchema: Schema<Resource> = typedExpandoObject(
  { id: ['id', optional(string())], type: ['type', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
