/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ResourcesInInfoFromAppsPermissionsInfo {
  excludedIds?: unknown[];
  ids: unknown[];
  wildcard?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const resourcesInInfoFromAppsPermissionsInfoSchema: Schema<ResourcesInInfoFromAppsPermissionsInfo> = typedExpandoObject(
  {
    excludedIds: ['excluded_ids', optional(array(unknown()))],
    ids: ['ids', array(unknown())],
    wildcard: ['wildcard', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
