/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ResponseMetadata {
  nextCursor: string;
  additionalProperties?: Record<string, unknown>;
}

export const responseMetadataSchema: Schema<ResponseMetadata> = typedExpandoObject(
  { nextCursor: ['next_cursor', string()] },
  'additionalProperties',
  optional(unknown())
);
