/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ResponseMetadata3 {
  warnings?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const responseMetadata3Schema: Schema<ResponseMetadata3> = typedExpandoObject(
  { warnings: ['warnings', optional(array(string()))] },
  'additionalProperties',
  optional(unknown())
);
