/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ScheduledMessage {
  channelId: string;
  dateCreated: number;
  id: string;
  postAt: number;
  text?: string;
  additionalProperties?: Record<string, unknown>;
}

export const scheduledMessageSchema: Schema<ScheduledMessage> = typedExpandoObject(
  {
    channelId: ['channel_id', string()],
    dateCreated: ['date_created', number()],
    id: ['id', string()],
    postAt: ['post_at', number()],
    text: ['text', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
