/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Scopes {
  appHome?: string[];
  channel?: string[];
  group?: string[];
  im?: string[];
  mpim?: string[];
  team?: string[];
  user?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const scopesSchema: Schema<Scopes> = typedExpandoObject(
  {
    appHome: ['app_home', optional(array(string()))],
    channel: ['channel', optional(array(string()))],
    group: ['group', optional(array(string()))],
    im: ['im', optional(array(string()))],
    mpim: ['mpim', optional(array(string()))],
    team: ['team', optional(array(string()))],
    user: ['user', optional(array(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
