/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Self {
  id: string;
  name: string;
  additionalProperties?: Record<string, unknown>;
}

export const selfSchema: Schema<Self> = typedExpandoObject(
  { id: ['id', string()], name: ['name', string()] },
  'additionalProperties',
  optional(unknown())
);
