/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { optional, Schema, typedExpandoObject, unknown } from '../schema.js';

export interface Shares {
  mPrivate?: unknown;
  mPublic?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const sharesSchema: Schema<Shares> = typedExpandoObject(
  {
    mPrivate: ['private', optional(unknown())],
    mPublic: ['public', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
