/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Prefs, prefsSchema } from './prefs.js';

export interface SubteamUsergroupObject {
  autoProvision: boolean;
  autoType?: unknown;
  channelCount?: number;
  createdBy: string;
  dateCreate: number;
  dateDelete: number;
  dateUpdate: number;
  deletedBy?: unknown;
  description: string;
  enterpriseSubteamId: string;
  handle: string;
  id: string;
  isExternal: boolean;
  isSubteam: boolean;
  isUsergroup: boolean;
  name: string;
  prefs: Prefs;
  teamId: string;
  updatedBy: string;
  userCount?: number;
  users?: string[];
  additionalProperties?: Record<string, unknown>;
}

export const subteamUsergroupObjectSchema: Schema<SubteamUsergroupObject> = lazy(
  () =>
    typedExpandoObject(
      {
        autoProvision: ['auto_provision', boolean()],
        autoType: ['auto_type', optional(unknown())],
        channelCount: ['channel_count', optional(number())],
        createdBy: ['created_by', string()],
        dateCreate: ['date_create', number()],
        dateDelete: ['date_delete', number()],
        dateUpdate: ['date_update', number()],
        deletedBy: ['deleted_by', optional(unknown())],
        description: ['description', string()],
        enterpriseSubteamId: ['enterprise_subteam_id', string()],
        handle: ['handle', string()],
        id: ['id', string()],
        isExternal: ['is_external', boolean()],
        isSubteam: ['is_subteam', boolean()],
        isUsergroup: ['is_usergroup', boolean()],
        name: ['name', string()],
        prefs: ['prefs', prefsSchema],
        teamId: ['team_id', string()],
        updatedBy: ['updated_by', string()],
        userCount: ['user_count', optional(number())],
        users: ['users', optional(array(string()))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
