/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Team1 {
  domain: string;
  id: string;
  name: string;
  additionalProperties?: Record<string, unknown>;
}

export const team1Schema: Schema<Team1> = typedExpandoObject(
  {
    domain: ['domain', string()],
    id: ['id', string()],
    name: ['name', string()],
  },
  'additionalProperties',
  optional(unknown())
);
