/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { TeamObject, teamObjectSchema } from './teamObject.js';

/** Schema for successful response from team.info method */
export interface TeamInfoSchema {
  ok: string;
  team: TeamObject;
  additionalProperties?: Record<string, unknown>;
}

export const teamInfoSchemaSchema: Schema<TeamInfoSchema> = lazy(() =>
  typedExpandoObject(
    { ok: ['ok', string()], team: ['team', teamObjectSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
