/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TeamProfileGetErrorEnum
 */
export enum TeamProfileGetErrorEnum {
  NotAuthed = 'not_authed',
  InvalidAuth = 'invalid_auth',
  AccountInactive = 'account_inactive',
  NoPermission = 'no_permission',
  UserIsBot = 'user_is_bot',
  InvalidArgName = 'invalid_arg_name',
  InvalidArrayArg = 'invalid_array_arg',
  InvalidCharset = 'invalid_charset',
  InvalidFormData = 'invalid_form_data',
  InvalidPostTyp = 'invalid_post_typ',
  MissingPostType = 'missing_post_type',
  TeamAddedToOrg = 'team_added_to_org',
  InvalidJson = 'invalid_json',
  JsonNotObject = 'json_not_object',
  RequestTimeou = 'request_timeou',
  UpgradeRequired = 'upgrade_required',
}

/**
 * Schema for TeamProfileGetErrorEnum
 */
export const teamProfileGetErrorEnumSchema: Schema<TeamProfileGetErrorEnum> = stringEnum(
  TeamProfileGetErrorEnum
);
