/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Login, loginSchema } from './login.js';
import { PagingObject, pagingObjectSchema } from './pagingObject.js';

/** Schema for successful response from team.accessLogs method */
export interface TeamAccessLogsSchema {
  logins: Login[];
  ok: string;
  paging: PagingObject;
  additionalProperties?: Record<string, unknown>;
}

export const teamAccessLogsSchemaSchema: Schema<TeamAccessLogsSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        logins: ['logins', array(loginSchema)],
        ok: ['ok', string()],
        paging: ['paging', pagingObjectSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
