/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Log, logSchema } from './log.js';
import { PagingObject, pagingObjectSchema } from './pagingObject.js';

/** Schema for successful response from team.integrationLogs method */
export interface TeamIntegrationLogsSchema {
  logs: Log[];
  ok: string;
  paging: PagingObject;
  additionalProperties?: Record<string, unknown>;
}

export const teamIntegrationLogsSchemaSchema: Schema<TeamIntegrationLogsSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        logs: ['logs', array(logSchema)],
        ok: ['ok', string()],
        paging: ['paging', pagingObjectSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
