/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Profile, profileSchema } from './profile.js';

/** Schema for successful response from team.profile.get method */
export interface TeamProfileGetSuccessSchema {
  ok: string;
  profile: Profile;
  additionalProperties?: Record<string, unknown>;
}

export const teamProfileGetSuccessSchemaSchema: Schema<TeamProfileGetSuccessSchema> = lazy(
  () =>
    typedExpandoObject(
      { ok: ['ok', string()], profile: ['profile', profileSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
