/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Topic {
  creator: string;
  lastSet: number;
  value: string;
  additionalProperties?: Record<string, unknown>;
}

export const topicSchema: Schema<Topic> = typedExpandoObject(
  {
    creator: ['creator', string()],
    lastSet: ['last_set', number()],
    value: ['value', string()],
  },
  'additionalProperties',
  optional(unknown())
);
