/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  UserProfileObject,
  userProfileObjectSchema,
} from './userProfileObject.js';

/** Schema for successful response from users.profile.set method */
export interface UsersProfileSetSchema {
  emailPending?: string;
  ok: string;
  profile: UserProfileObject;
  username: string;
  additionalProperties?: Record<string, unknown>;
}

export const usersProfileSetSchemaSchema: Schema<UsersProfileSetSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        emailPending: ['email_pending', optional(string())],
        ok: ['ok', string()],
        profile: ['profile', userProfileObjectSchema],
        username: ['username', string()],
      },
      'additionalProperties',
      optional(unknown())
    )
);
