/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response from users.info method */
export interface UsersInfoSuccessSchema {
  ok: string;
  user?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const usersInfoSuccessSchemaSchema: Schema<UsersInfoSuccessSchema> = typedExpandoObject(
  { ok: ['ok', string()], user: ['user', optional(unknown())] },
  'additionalProperties',
  optional(unknown())
);
