/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response from users.list method */
export interface UsersListSchema {
  cacheTs: number;
  members: unknown[];
  ok: string;
  responseMetadata?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export const usersListSchemaSchema: Schema<UsersListSchema> = typedExpandoObject(
  {
    cacheTs: ['cache_ts', number()],
    members: ['members', array(unknown())],
    ok: ['ok', string()],
    responseMetadata: ['response_metadata', optional(unknown())],
  },
  'additionalProperties',
  optional(unknown())
);
