/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SubteamUsergroupObject,
  subteamUsergroupObjectSchema,
} from './subteamUsergroupObject.js';

/** Schema for successful response from usergroups.list method */
export interface UsergroupsListSchema {
  ok: string;
  usergroups: SubteamUsergroupObject[];
  additionalProperties?: Record<string, unknown>;
}

export const usergroupsListSchemaSchema: Schema<UsergroupsListSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        ok: ['ok', string()],
        usergroups: ['usergroups', array(subteamUsergroupObjectSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
