/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for UsersLookupByEmailErrorEnum
 */
export enum UsersLookupByEmailErrorEnum {
  UsersNotFound = 'users_not_found',
  EnterpriseIsRestricted = 'enterprise_is_restricted',
  NotAuthed = 'not_authed',
  InvalidAuth = 'invalid_auth',
  AccountInactive = 'account_inactive',
  NoPermission = 'no_permission',
  InvalidArgName = 'invalid_arg_name',
  InvalidArrayArg = 'invalid_array_arg',
  InvalidCharset = 'invalid_charset',
  InvalidFormData = 'invalid_form_data',
  InvalidPostType = 'invalid_post_type',
  MissingPostType = 'missing_post_type',
  TeamAddedToOrg = 'team_added_to_org',
  InvalidJson = 'invalid_json',
  JsonNotObject = 'json_not_object',
  RequestTimeout = 'request_timeout',
  UpgradeRequired = 'upgrade_required',
  FatalError = 'fatal_error',
}

/**
 * Schema for UsersLookupByEmailErrorEnum
 */
export const usersLookupByEmailErrorEnumSchema: Schema<UsersLookupByEmailErrorEnum> = stringEnum(
  UsersLookupByEmailErrorEnum
);
