/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface UserProfileObject {
  alwaysActive?: boolean;
  apiAppId?: string;
  avatarHash: string;
  botId?: string;
  displayName: string;
  displayNameNormalized: string;
  email?: string | null;
  fields: unknown[] | null;
  firstName?: string | null;
  guestExpirationTs?: number | null;
  guestInvitedBy?: string | null;
  image1024?: string | null;
  image192?: string | null;
  image24?: string | null;
  image32?: string | null;
  image48?: string | null;
  image512?: string | null;
  image72?: string | null;
  imageOriginal?: string | null;
  isAppUser?: boolean;
  isCustomImage?: boolean;
  isRestricted?: boolean | null;
  isUltraRestricted?: boolean | null;
  lastAvatarImageHash?: string;
  lastName?: string | null;
  membershipsCount?: number;
  name?: string | null;
  phone: string;
  pronouns?: string;
  realName: string;
  realNameNormalized: string;
  skype: string;
  statusDefaultEmoji?: string;
  statusDefaultText?: string;
  statusDefaultTextCanonical?: string | null;
  statusEmoji: string;
  statusExpiration?: number;
  statusText: string;
  statusTextCanonical?: string | null;
  team?: string;
  title: string;
  updated?: number;
  userId?: string;
  username?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const userProfileObjectSchema: Schema<UserProfileObject> = typedExpandoObject(
  {
    alwaysActive: ['always_active', optional(boolean())],
    apiAppId: ['api_app_id', optional(string())],
    avatarHash: ['avatar_hash', string()],
    botId: ['bot_id', optional(string())],
    displayName: ['display_name', string()],
    displayNameNormalized: ['display_name_normalized', string()],
    email: ['email', optional(nullable(string()))],
    fields: ['fields', nullable(array(unknown()))],
    firstName: ['first_name', optional(nullable(string()))],
    guestExpirationTs: ['guest_expiration_ts', optional(nullable(number()))],
    guestInvitedBy: ['guest_invited_by', optional(nullable(string()))],
    image1024: ['image_1024', optional(nullable(string()))],
    image192: ['image_192', optional(nullable(string()))],
    image24: ['image_24', optional(nullable(string()))],
    image32: ['image_32', optional(nullable(string()))],
    image48: ['image_48', optional(nullable(string()))],
    image512: ['image_512', optional(nullable(string()))],
    image72: ['image_72', optional(nullable(string()))],
    imageOriginal: ['image_original', optional(nullable(string()))],
    isAppUser: ['is_app_user', optional(boolean())],
    isCustomImage: ['is_custom_image', optional(boolean())],
    isRestricted: ['is_restricted', optional(nullable(boolean()))],
    isUltraRestricted: ['is_ultra_restricted', optional(nullable(boolean()))],
    lastAvatarImageHash: ['last_avatar_image_hash', optional(string())],
    lastName: ['last_name', optional(nullable(string()))],
    membershipsCount: ['memberships_count', optional(number())],
    name: ['name', optional(nullable(string()))],
    phone: ['phone', string()],
    pronouns: ['pronouns', optional(string())],
    realName: ['real_name', string()],
    realNameNormalized: ['real_name_normalized', string()],
    skype: ['skype', string()],
    statusDefaultEmoji: ['status_default_emoji', optional(string())],
    statusDefaultText: ['status_default_text', optional(string())],
    statusDefaultTextCanonical: [
      'status_default_text_canonical',
      optional(nullable(string())),
    ],
    statusEmoji: ['status_emoji', string()],
    statusExpiration: ['status_expiration', optional(number())],
    statusText: ['status_text', string()],
    statusTextCanonical: [
      'status_text_canonical',
      optional(nullable(string())),
    ],
    team: ['team', optional(string())],
    title: ['title', string()],
    updated: ['updated', optional(number())],
    userId: ['user_id', optional(string())],
    username: ['username', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
