/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  SubteamUsergroupObject,
  subteamUsergroupObjectSchema,
} from './subteamUsergroupObject.js';

/** Schema for successful response from usergroups.enable method */
export interface UsergroupsEnableSchema {
  ok: string;
  usergroup: SubteamUsergroupObject;
  additionalProperties?: Record<string, unknown>;
}

export const usergroupsEnableSchemaSchema: Schema<UsergroupsEnableSchema> = lazy(
  () =>
    typedExpandoObject(
      {
        ok: ['ok', string()],
        usergroup: ['usergroup', subteamUsergroupObjectSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
