/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Schema for successful response from usergroups.users.list method */
export interface UsergroupsUsersListSchema {
  ok: string;
  users: string[];
  additionalProperties?: Record<string, unknown>;
}

export const usergroupsUsersListSchemaSchema: Schema<UsergroupsUsersListSchema> = typedExpandoObject(
  { ok: ['ok', string()], users: ['users', array(string())] },
  'additionalProperties',
  optional(unknown())
);
