/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Profile1, profile1Schema } from './profile1.js';

/** Schema for successful response from users.setPhoto method */
export interface UsersSetPhotoSchema {
  ok: string;
  profile: Profile1;
  additionalProperties?: Record<string, unknown>;
}

export const usersSetPhotoSchemaSchema: Schema<UsersSetPhotoSchema> = lazy(() =>
  typedExpandoObject(
    { ok: ['ok', string()], profile: ['profile', profile1Schema] },
    'additionalProperties',
    optional(unknown())
  )
);
