/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  UserProfileObject,
  userProfileObjectSchema,
} from './userProfileObject.js';

/** Schema for successful response from users.profile.get method */
export interface UsersProfileGetSchema {
  ok: string;
  profile: UserProfileObject;
  additionalProperties?: Record<string, unknown>;
}

export const usersProfileGetSchemaSchema: Schema<UsersProfileGetSchema> = lazy(
  () =>
    typedExpandoObject(
      { ok: ['ok', string()], profile: ['profile', userProfileObjectSchema] },
      'additionalProperties',
      optional(unknown())
    )
);
