/**
 * Slack Web APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  compositeAuthenticationProvider,
  OAuthConfiguration,
  requestAuthenticationProvider,
} from './authentication.js';
import { AuthorizationCodeAuthManager } from './authorizationCodeAuthManager.js';
import { Configuration } from './configuration.js';
import { OauthToken } from './models/oauthToken.js';

export function createAuthProviderFromConfig(
  config: Partial<Configuration>,
  slackAuth: () => AuthorizationCodeAuthManager
) {
  const authConfig = {
    slackAuth:
      config.authorizationCodeAuthCredentials &&
      requestAuthenticationProvider(
        config.authorizationCodeAuthCredentials.oauthToken,
        slackAuthTokenProvider(
          slackAuth,
          config.authorizationCodeAuthCredentials.oauthTokenProvider
        ),
        config.authorizationCodeAuthCredentials.oauthOnTokenUpdate,
        {
          clockSkew: config.authorizationCodeAuthCredentials.oauthClockSkew,
        } as OAuthConfiguration
      ),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}

function slackAuthTokenProvider(
  slackAuth: () => AuthorizationCodeAuthManager,
  defaultProvider:
    | ((
        lastOAuthToken: OauthToken | undefined,
        authManager: AuthorizationCodeAuthManager
      ) => Promise<OauthToken>)
    | undefined
): ((token: OauthToken | undefined) => Promise<OauthToken>) | undefined {
  return (token: OauthToken | undefined) => {
    const manager = slackAuth();
    if (defaultProvider === undefined) {
      return manager.updateToken(token);
    }
    return defaultProvider(token, manager);
  };
}
